// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.TicketingModule.Domain.Entities;
using QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.Booking;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Application.Services.Booking
{
    public partial class BookingService : IBookingService
    {
        private readonly ILogger<BookingService> _logger;
        private readonly IBookingRepository _repository;
        public BookingService(ILogger<BookingService> logger, IBookingRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<BookingDto>> InsertAsync(BookingDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(BookingDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, BookingDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<BookingDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<BookingDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByCustomerResponseDto>>> GetByCustomerAsync(int bookingCustomerId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByCustomerAsync(bookingCustomerId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByScheduleResponseDto>>> GetByScheduleAsync(int bookingScheduleId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByScheduleAsync(bookingScheduleId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetPendingResponseDto>>> GetPendingAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetPendingAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetConfirmedResponseDto>>> GetConfirmedAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetConfirmedAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetExpiredResponseDto>>> GetExpiredAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetExpiredAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetPendingExpiringResponseDto>>> GetPendingExpiringAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetPendingExpiringAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetTodayBookingsResponseDto>>> GetTodayBookingsAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetTodayBookingsAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetBookingSummaryResponseDto>> GetBookingSummaryAsync(int bookingScheduleId)
        {
            var returnValue = await _repository.GetBookingSummaryAsync(bookingScheduleId);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetMonthlyBookingStatsResponseDto>> GetMonthlyBookingStatsAsync()
        {
            var returnValue = await _repository.GetMonthlyBookingStatsAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> ConfirmAsync(int bookingId, ConfirmRequestDto updateRequest)
        {
            var returnValue = await _repository.ConfirmAsync(bookingId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> MarkExpiredAsync(int bookingId, MarkExpiredRequestDto updateRequest)
        {
            var returnValue = await _repository.MarkExpiredAsync(bookingId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> CancelAsync(int bookingId, CancelRequestDto updateRequest)
        {
            var returnValue = await _repository.CancelAsync(bookingId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> CompleteAsync(int bookingId, CompleteRequestDto updateRequest)
        {
            var returnValue = await _repository.CompleteAsync(bookingId, updateRequest);
            return returnValue.ToResponse();
        }
    }
}