// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Application.Dtos.PaymentRecord
{
    public record GetByDateRangeResponseDto
    {
        public int Id { get; init; }
        public int BookingId { get; init; }
        public decimal Amount { get; init; }
        public string PaymentMethod { get; init; }
        public DateTime PaymentDate { get; init; }
    }
}