-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [NAME],
    [DESCRIPTION],
    [EVENT_TYPE],
    [STATUS],
    [DURATION_MINUTES],
    [POSTER_URL],
    [IS_ACTIVE],
    [CREATED_DATE],
    [UPDATED_DATE]
FROM [dbo].[EVENT_ITEMS]
WHERE
    [ID] = @PRM_EVENT_ITEM_ID
    AND [IsDeleted] = 0;