-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[EVENT_ITEMS] (
    [NAME],
    [DESCRIPTION],
    [EVENT_TYPE],
    [STATUS],
    [DURATION_MINUTES],
    [POSTER_URL],
    [IS_ACTIVE],
    [CREATED_DATE],
    [UPDATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_EVENT_ITEM_NAME,
    @PRM_EVENT_ITEM_DESCRIPTION,
    @PRM_EVENT_ITEM_EVENT_TYPE,
    @PRM_EVENT_ITEM_STATUS,
    @PRM_EVENT_ITEM_DURATION_MINUTES,
    @PRM_EVENT_ITEM_POSTER_URL,
    @PRM_EVENT_ITEM_IS_ACTIVE,
    @PRM_EVENT_ITEM_CREATED_DATE,
    @PRM_EVENT_ITEM_UPDATED_DATE
    );