// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QcEntity = global::QuickCode.BirBilet.TicketingModule.Domain.Entities;
using QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.Booking;
using QuickCode.BirBilet.TicketingModule.Application.Mappings;
using QuickCode.BirBilet.TicketingModule.Persistence.Sql;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Persistence.Repositories
{
    public partial class BookingRepository : BaseRepository, IBookingRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public BookingRepository(ILogger<BookingRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "Booking")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<BookingDto>> InsertAsync(BookingDto value)
        {
            return await ExecuteWithExceptionHandling(BookingCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Booking.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(BookingCrudSqlBindings.ParameterNamePrefix, value, BookingCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.Booking>(sql, p);
                return new RepoResponse<BookingDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(BookingDto value)
        {
            return await ExecuteWithExceptionHandling(BookingCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Booking.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(BookingCrudSqlBindings.ParameterNamePrefix, value, BookingCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(BookingDto value)
        {
            return await ExecuteWithExceptionHandling(BookingCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Booking.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(BookingCrudSqlBindings.ParameterNamePrefix, value, BookingCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<BookingDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(BookingCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Booking.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(BookingCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.Booking>(sql, p);
                return row == null ? CreateNotFoundResponse<BookingDto>("Not found in Booking") : new RepoResponse<BookingDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<BookingDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(BookingCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<BookingDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.Booking.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.Booking>(sql, p);
                return new RepoResponse<List<BookingDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(BookingCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Booking.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}