// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirBilet.EventManagementModule.Domain;
using QuickCode.BirBilet.Domain.Shared.Abstractions;
using QuickCode.BirBilet.Domain.Shared.Entities;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Domain.Entities;

[Table("EVENT_ITEMS")]
public partial class EventItem : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("NAME")]
	[StringLength(250)]
	public string Name { get; set; }
	
	[Column("DESCRIPTION")]
	[StringLength(1000)]
	public string Description { get; set; }
	
	[Column("EVENT_TYPE", TypeName = "nvarchar(50)")]
	public EventKind EventType { get; set; }
	
	[Column("STATUS", TypeName = "nvarchar(50)")]
	public EventStatus Status { get; set; }
	
	[Column("DURATION_MINUTES")]
	public int DurationMinutes { get; set; }
	
	[Column("POSTER_URL")]
	[StringLength(1000)]
	public string PosterUrl { get; set; }
	
	[Column("IS_ACTIVE")]
	public bool IsActive { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	
	[Column("UPDATED_DATE")]
	public DateTime UpdatedDate { get; set; }
	
	[InverseProperty(nameof(Schedule.EventItem))]
	public virtual ICollection<Schedule> Schedules { get; } = new List<Schedule>();
}

