// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirBilet.EventManagementModule.Domain;
using QuickCode.BirBilet.Domain.Shared.Abstractions;
using QuickCode.BirBilet.Domain.Shared.Entities;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Domain.Entities;

[Table("SCHEDULES")]
public partial class Schedule : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("EVENT_ID")]
	public int EventId { get; set; }
	
	[Column("VENUE_ID")]
	public int VenueId { get; set; }
	
	[Column("HALL_ID")]
	public int HallId { get; set; }
	
	[Column("SCHEDULE_DATE")]
	public DateTime ScheduleDate { get; set; }
	
	[Column("START_TIME")]
	public DateTime StartTime { get; set; }
	
	[Column("END_TIME")]
	public DateTime EndTime { get; set; }
	
	[Column("STATUS", TypeName = "nvarchar(50)")]
	public ScheduleStatus Status { get; set; }
	
	[Column("TOTAL_SEATS")]
	public int TotalSeats { get; set; }
	
	[Column("AVAILABLE_SEATS")]
	public int AvailableSeats { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	
	[InverseProperty(nameof(ScheduleHistory.Schedule))]
	public virtual ICollection<ScheduleHistory> ScheduleHistories { get; } = new List<ScheduleHistory>();

	[ForeignKey("EventId")]
	[InverseProperty(nameof(EventItem.Schedules))]
	public virtual EventItem EventItem { get; set; } = null!;
}

