// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.EventManagementModule.Domain.Entities;
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.EventItem;
using System.Threading.Tasks;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Application.Interfaces.Repositories
{
    public partial interface IEventItemRepository : IBaseRepository<EventItemDto>
    {
        Task<RepoResponse<EventItemDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByTypeResponseDto>>> GetByTypeAsync(EventKind eventItemEventType, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetPublishedResponseDto>>> GetPublishedAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string eventItemName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetRecentResponseDto>>> GetRecentAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetUpcomingResponseDto>>> GetUpcomingAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetTotalByTypeResponseDto>> GetTotalByTypeAsync(EventKind eventItemEventType);
        Task<RepoResponse<int>> PublishAsync(int eventItemId, PublishRequestDto updateRequest);
        Task<RepoResponse<int>> CancelAsync(int eventItemId, CancelRequestDto updateRequest);
        Task<RepoResponse<int>> MarkCompletedAsync(int eventItemId, MarkCompletedRequestDto updateRequest);
        Task<RepoResponse<int>> DeactivateAsync(int eventItemId);
    }
}