// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.EventManagementModule.Domain.Entities;
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.ScheduleHistory;
using System.Threading.Tasks;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Application.Interfaces.Repositories
{
    public partial interface IScheduleHistoryRepository : IBaseRepository<ScheduleHistoryDto>
    {
        Task<RepoResponse<ScheduleHistoryDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByScheduleResponseDto>>> GetByScheduleAsync(int scheduleHistoryScheduleId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetRecentChangesResponseDto>>> GetRecentChangesAsync(int? pageNumber = null, int? pageSize = null);
    }
}