// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.VenueManagementModule.Domain.Entities;
using QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.SeatCategory;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Application.Services.SeatCategory
{
    public partial interface ISeatCategoryService
    {
        Task<Response<SeatCategoryDto>> InsertAsync(SeatCategoryDto request);
        Task<Response<bool>> DeleteAsync(SeatCategoryDto request);
        Task<Response<bool>> UpdateAsync(int id, SeatCategoryDto request);
        Task<Response<List<SeatCategoryDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<SeatCategoryDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber, int? pageSize);
        Task<Response<int>> DeactivateAsync(int seatCategoryId, DeactivateRequestDto updateRequest);
    }
}