// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.VenueManagementModule.Domain.Entities;
using QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.VenueAmenity;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Application.Services.VenueAmenity
{
    public partial interface IVenueAmenityService
    {
        Task<Response<VenueAmenityDto>> InsertAsync(VenueAmenityDto request);
        Task<Response<bool>> DeleteAsync(VenueAmenityDto request);
        Task<Response<bool>> UpdateAsync(int id, VenueAmenityDto request);
        Task<Response<List<VenueAmenityDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<VenueAmenityDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetByVenueResponseDto>>> GetByVenueAsync(int venueAmenityVenueId, int? pageNumber, int? pageSize);
        Task<Response<List<GetAvailableResponseDto>>> GetAvailableAsync(int venueAmenityVenueId, int? pageNumber, int? pageSize);
        Task<Response<int>> MarkUnavailableAsync(int venueAmenityId, MarkUnavailableRequestDto updateRequest);
    }
}