// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.VenueManagementModule.Domain.Entities;
using QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Venue;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Application.Services.Venue
{
    public partial interface IVenueService
    {
        Task<Response<VenueDto>> InsertAsync(VenueDto request);
        Task<Response<bool>> DeleteAsync(VenueDto request);
        Task<Response<bool>> UpdateAsync(int id, VenueDto request);
        Task<Response<List<VenueDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<VenueDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber, int? pageSize);
        Task<Response<List<GetByCityResponseDto>>> GetByCityAsync(string venueCity, int? pageNumber, int? pageSize);
        Task<Response<List<GetByTypeResponseDto>>> GetByTypeAsync(VenueType venueVenueType, int? pageNumber, int? pageSize);
        Task<Response<List<SearchByNameResponseDto>>> SearchByNameAsync(string venueName, int? pageNumber, int? pageSize);
        Task<Response<List<GetWithContactResponseDto>>> GetWithContactAsync(int? pageNumber, int? pageSize);
        Task<Response<int>> DeactivateAsync(int venueId, DeactivateRequestDto updateRequest);
        Task<Response<int>> UpdateContactAsync(int venueId, UpdateContactRequestDto updateRequest);
    }
}