// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.VenueManagementModule.Domain.Entities;
using QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Seat;
using QuickCode.BirBilet.VenueManagementModule.Application.Mappings;
using QuickCode.BirBilet.VenueManagementModule.Persistence.Sql;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Persistence.Repositories
{
    public partial class SeatRepository : BaseRepository, ISeatRepository
    {
        public async Task<RepoResponse<List<GetByHallResponseDto>>> GetByHallAsync(int seatHallId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SeatCrudSqlBindings.OperationNames.GetByHall, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByHallResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Seat.Query.GetByHall);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SEAT_HALL_ID = seatHallId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByHallResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Seat");
                }
            });
        }

        public async Task<RepoResponse<List<GetAvailableResponseDto>>> GetAvailableAsync(int seatHallId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SeatCrudSqlBindings.OperationNames.GetAvailable, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetAvailableResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Seat.Query.GetAvailable);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SEAT_HALL_ID = seatHallId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetAvailableResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Seat");
                }
            });
        }

        public async Task<RepoResponse<List<GetByCategoryResponseDto>>> GetByCategoryAsync(int seatHallId, SeatCategoryKind seatCategory, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SeatCrudSqlBindings.OperationNames.GetByCategory, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCategoryResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Seat.Query.GetByCategory);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SEAT_HALL_ID = seatHallId,
                        PRM_SEAT_CATEGORY = seatCategory,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByCategoryResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Seat");
                }
            });
        }

        public async Task<RepoResponse<List<GetPremiumSeatsResponseDto>>> GetPremiumSeatsAsync(int seatHallId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SeatCrudSqlBindings.OperationNames.GetPremiumSeats, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetPremiumSeatsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Seat.Query.GetPremiumSeats);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SEAT_HALL_ID = seatHallId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetPremiumSeatsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Seat");
                }
            });
        }

        public async Task<RepoResponse<List<GetDisabledAccessResponseDto>>> GetDisabledAccessAsync(int seatHallId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SeatCrudSqlBindings.OperationNames.GetDisabledAccess, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetDisabledAccessResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Seat.Query.GetDisabledAccess);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SEAT_HALL_ID = seatHallId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetDisabledAccessResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Seat");
                }
            });
        }

        public async Task<RepoResponse<List<GetAvailableByRowResponseDto>>> GetAvailableByRowAsync(int seatHallId, string seatRowNumber, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SeatCrudSqlBindings.OperationNames.GetAvailableByRow, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetAvailableByRowResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Seat.Query.GetAvailableByRow);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SEAT_HALL_ID = seatHallId,
                        PRM_SEAT_ROW_NUMBER = seatRowNumber,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetAvailableByRowResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Seat");
                }
            });
        }

        public async Task<RepoResponse<GetCategoryBreakdownResponseDto>> GetCategoryBreakdownAsync(int seatHallId)
        {
            return await ExecuteWithExceptionHandling(SeatCrudSqlBindings.OperationNames.GetCategoryBreakdown, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Seat.Query.GetCategoryBreakdown);
                var parameters = new
                {
                    PRM_SEAT_HALL_ID = seatHallId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetCategoryBreakdownResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Seat");
            });
        }
    }
}