// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Seat;

namespace QuickCode.BirBilet.VenueManagementModule.Persistence.Repositories;
internal static class SeatCrudSqlBindings
{
    public const string StoreTableName = "SEATS";
    public const string ParameterNamePrefix = "SEAT";
    public const string IdParameterName = "PRM_SEAT_ID";
    public static class OperationNames
    {
        public const string BlockSeat = "BlockSeat";
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetAvailable = "GetAvailable";
        public const string GetAvailableByRow = "GetAvailableByRow";
        public const string GetByCategory = "GetByCategory";
        public const string GetByHall = "GetByHall";
        public const string GetByPk = "GetByPk";
        public const string GetCategoryBreakdown = "GetCategoryBreakdown";
        public const string GetDisabledAccess = "GetDisabledAccess";
        public const string GetPremiumSeats = "GetPremiumSeats";
        public const string Insert = "Insert";
        public const string MarkAvailable = "MarkAvailable";
        public const string MarkReserved = "MarkReserved";
        public const string MarkSold = "MarkSold";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("HALL_ID", nameof(SeatDto.HallId)),
        ("SEAT_NUMBER", nameof(SeatDto.SeatNumber)),
        ("ROW_NUMBER", nameof(SeatDto.RowNumber)),
        ("COLUMN_NUMBER", nameof(SeatDto.ColumnNumber)),
        ("CATEGORY", nameof(SeatDto.Category)),
        ("STATUS", nameof(SeatDto.Status)),
        ("IS_ACTIVE", nameof(SeatDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("HALL_ID", nameof(SeatDto.HallId)),
        ("SEAT_NUMBER", nameof(SeatDto.SeatNumber)),
        ("ROW_NUMBER", nameof(SeatDto.RowNumber)),
        ("COLUMN_NUMBER", nameof(SeatDto.ColumnNumber)),
        ("CATEGORY", nameof(SeatDto.Category)),
        ("STATUS", nameof(SeatDto.Status)),
        ("IS_ACTIVE", nameof(SeatDto.IsActive)),
        ("ID", nameof(SeatDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(SeatDto.Id))
    };
}