// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.PaymentRecord;
using PaymentRecordEntity = QuickCode.BirBilet.TicketingModule.Domain.Entities.PaymentRecord;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Application.Mappings
{
    public static class PaymentRecordMappings
    {
        public static List<PaymentRecordDto> ToDto(this IEnumerable<PaymentRecordEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PaymentRecordDto ToDto(this PaymentRecordEntity model)
        {
            return new PaymentRecordDto
            {
                Id = model.Id,
                BookingId = model.BookingId,
                Amount = model.Amount,
                PaymentMethod = model.PaymentMethod,
                TransactionId = model.TransactionId,
                PaymentDate = model.PaymentDate,
                Status = model.Status,
                CreatedDate = model.CreatedDate
            };
        }

        public static PaymentRecordEntity ToEntity(this PaymentRecordDto model)
        {
            return new PaymentRecordEntity
            {
                Id = model.Id,
                BookingId = model.BookingId,
                Amount = model.Amount,
                PaymentMethod = model.PaymentMethod,
                TransactionId = model.TransactionId,
                PaymentDate = model.PaymentDate,
                Status = model.Status,
                CreatedDate = model.CreatedDate
            };
        }
    }
}