// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.Pricing;
using PricingEntity = QuickCode.BirBilet.TicketingModule.Domain.Entities.Pricing;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Application.Mappings
{
    public static class PricingMappings
    {
        public static List<PricingDto> ToDto(this IEnumerable<PricingEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PricingDto ToDto(this PricingEntity model)
        {
            return new PricingDto
            {
                Id = model.Id,
                ScheduleId = model.ScheduleId,
                SeatCategory = model.SeatCategory,
                PriceType = model.PriceType,
                BasePrice = model.BasePrice,
                DiscountPercentage = model.DiscountPercentage,
                FinalPrice = model.FinalPrice,
                ValidFrom = model.ValidFrom,
                ValidTo = model.ValidTo,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static PricingEntity ToEntity(this PricingDto model)
        {
            return new PricingEntity
            {
                Id = model.Id,
                ScheduleId = model.ScheduleId,
                SeatCategory = model.SeatCategory,
                PriceType = model.PriceType,
                BasePrice = model.BasePrice,
                DiscountPercentage = model.DiscountPercentage,
                FinalPrice = model.FinalPrice,
                ValidFrom = model.ValidFrom,
                ValidTo = model.ValidTo,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}