// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QcEntity = global::QuickCode.BirBilet.VenueManagementModule.Domain.Entities;
using QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.VenueAmenity;
using QuickCode.BirBilet.VenueManagementModule.Application.Mappings;
using QuickCode.BirBilet.VenueManagementModule.Persistence.Sql;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Persistence.Repositories
{
    public partial class VenueAmenityRepository : BaseRepository, IVenueAmenityRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public VenueAmenityRepository(ILogger<VenueAmenityRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "VenueAmenity")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<VenueAmenityDto>> InsertAsync(VenueAmenityDto value)
        {
            return await ExecuteWithExceptionHandling(VenueAmenityCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.VenueAmenity.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(VenueAmenityCrudSqlBindings.ParameterNamePrefix, value, VenueAmenityCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.VenueAmenity>(sql, p);
                return new RepoResponse<VenueAmenityDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(VenueAmenityDto value)
        {
            return await ExecuteWithExceptionHandling(VenueAmenityCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.VenueAmenity.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(VenueAmenityCrudSqlBindings.ParameterNamePrefix, value, VenueAmenityCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(VenueAmenityDto value)
        {
            return await ExecuteWithExceptionHandling(VenueAmenityCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.VenueAmenity.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(VenueAmenityCrudSqlBindings.ParameterNamePrefix, value, VenueAmenityCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<VenueAmenityDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(VenueAmenityCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.VenueAmenity.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(VenueAmenityCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.VenueAmenity>(sql, p);
                return row == null ? CreateNotFoundResponse<VenueAmenityDto>("Not found in VenueAmenity") : new RepoResponse<VenueAmenityDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<VenueAmenityDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(VenueAmenityCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<VenueAmenityDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.VenueAmenity.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.VenueAmenity>(sql, p);
                return new RepoResponse<List<VenueAmenityDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(VenueAmenityCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.VenueAmenity.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}