// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.Schedule;
using ScheduleEntity = QuickCode.BirBilet.EventManagementModule.Domain.Entities.Schedule;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Application.Mappings
{
    public static class ScheduleMappings
    {
        public static List<ScheduleDto> ToDto(this IEnumerable<ScheduleEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ScheduleDto ToDto(this ScheduleEntity model)
        {
            return new ScheduleDto
            {
                Id = model.Id,
                EventId = model.EventId,
                VenueId = model.VenueId,
                HallId = model.HallId,
                ScheduleDate = model.ScheduleDate,
                StartTime = model.StartTime,
                EndTime = model.EndTime,
                Status = model.Status,
                TotalSeats = model.TotalSeats,
                AvailableSeats = model.AvailableSeats,
                CreatedDate = model.CreatedDate
            };
        }

        public static ScheduleEntity ToEntity(this ScheduleDto model)
        {
            return new ScheduleEntity
            {
                Id = model.Id,
                EventId = model.EventId,
                VenueId = model.VenueId,
                HallId = model.HallId,
                ScheduleDate = model.ScheduleDate,
                StartTime = model.StartTime,
                EndTime = model.EndTime,
                Status = model.Status,
                TotalSeats = model.TotalSeats,
                AvailableSeats = model.AvailableSeats,
                CreatedDate = model.CreatedDate
            };
        }
    }
}