// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.ScheduleHistory;
using ScheduleHistoryEntity = QuickCode.BirBilet.EventManagementModule.Domain.Entities.ScheduleHistory;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Application.Mappings
{
    public static class ScheduleHistoryMappings
    {
        public static List<ScheduleHistoryDto> ToDto(this IEnumerable<ScheduleHistoryEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ScheduleHistoryDto ToDto(this ScheduleHistoryEntity model)
        {
            return new ScheduleHistoryDto
            {
                Id = model.Id,
                ScheduleId = model.ScheduleId,
                PreviousStatus = model.PreviousStatus,
                NewStatus = model.NewStatus,
                ChangedDate = model.ChangedDate,
                ChangeReason = model.ChangeReason
            };
        }

        public static ScheduleHistoryEntity ToEntity(this ScheduleHistoryDto model)
        {
            return new ScheduleHistoryEntity
            {
                Id = model.Id,
                ScheduleId = model.ScheduleId,
                PreviousStatus = model.PreviousStatus,
                NewStatus = model.NewStatus,
                ChangedDate = model.ChangedDate,
                ChangeReason = model.ChangeReason
            };
        }
    }
}