// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.VenueManagementModule.Domain.Entities;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Venue;
using System.Threading.Tasks;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories
{
    public partial interface IVenueRepository : IBaseRepository<VenueDto>
    {
        Task<RepoResponse<VenueDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByCityResponseDto>>> GetByCityAsync(string venueCity, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByTypeResponseDto>>> GetByTypeAsync(VenueType venueVenueType, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string venueName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetWithContactResponseDto>>> GetWithContactAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> DeactivateAsync(int venueId, DeactivateRequestDto updateRequest);
        Task<RepoResponse<int>> UpdateContactAsync(int venueId, UpdateContactRequestDto updateRequest);
    }
}