-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[HALLS] (
    [VENUE_ID],
    [HALL_NAME],
    [HALL_NUMBER],
    [CAPACITY],
    [TOTAL_ROWS],
    [TOTAL_COLUMNS],
    [STATUS],
    [IS_ACTIVE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_HALL_VENUE_ID,
    @PRM_HALL_HALL_NAME,
    @PRM_HALL_HALL_NUMBER,
    @PRM_HALL_CAPACITY,
    @PRM_HALL_TOTAL_ROWS,
    @PRM_HALL_TOTAL_COLUMNS,
    @PRM_HALL_STATUS,
    @PRM_HALL_IS_ACTIVE,
    @PRM_HALL_CREATED_DATE
    );