IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.VENUES', N'U') AND name = N'IX_VENUES_CITY')
BEGIN
    CREATE INDEX [IX_VENUES_CITY] ON [dbo].[VENUES] ([CITY]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.VENUES', N'U') AND name = N'IX_VENUES_VENUE_TYPE')
BEGIN
    CREATE INDEX [IX_VENUES_VENUE_TYPE] ON [dbo].[VENUES] ([VENUE_TYPE]);
END