IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.VENUE_AMENITIES', N'U') AND name = N'IX_VENUE_AMENITIES_IsDeleted')
BEGIN
    CREATE INDEX [IX_VENUE_AMENITIES_IsDeleted] ON [dbo].[VENUE_AMENITIES] ([IsDeleted]);
END