IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SEATS', N'U') AND name = N'IX_SEATS_HALL_ID_CATEGORY')
BEGIN
    CREATE INDEX [IX_SEATS_HALL_ID_CATEGORY] ON [dbo].[SEATS] ([HALL_ID], [CATEGORY]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SEATS', N'U') AND name = N'IX_SEATS_HALL_ID_ROW_NUMBER_STATUS')
BEGIN
    CREATE INDEX [IX_SEATS_HALL_ID_ROW_NUMBER_STATUS] ON [dbo].[SEATS] ([HALL_ID], [ROW_NUMBER], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SEATS', N'U') AND name = N'IX_SEATS_HALL_ID_STATUS')
BEGIN
    CREATE INDEX [IX_SEATS_HALL_ID_STATUS] ON [dbo].[SEATS] ([HALL_ID], [STATUS]);
END