IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SEATS_HALLS_HALL_ID' AND parent_object_id = OBJECT_ID(N'dbo.SEATS'))
BEGIN
    ALTER TABLE [dbo].[SEATS] ADD CONSTRAINT [FK_SEATS_HALLS_HALL_ID] FOREIGN KEY ([HALL_ID]) REFERENCES [dbo].[HALLS] ([ID]);
END