IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.HALLS', N'U') AND name = N'IX_HALLS_VENUE_ID_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_HALLS_VENUE_ID_IS_ACTIVE] ON [dbo].[HALLS] ([VENUE_ID], [IS_ACTIVE]);
END