IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SEAT_CATEGORIES', N'U') AND name = N'IX_SEAT_CATEGORIES_IsDeleted')
BEGIN
    CREATE INDEX [IX_SEAT_CATEGORIES_IsDeleted] ON [dbo].[SEAT_CATEGORIES] ([IsDeleted]);
END