IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_HALLS_VENUES_VENUE_ID' AND parent_object_id = OBJECT_ID(N'dbo.HALLS'))
BEGIN
    ALTER TABLE [dbo].[HALLS] ADD CONSTRAINT [FK_HALLS_VENUES_VENUE_ID] FOREIGN KEY ([VENUE_ID]) REFERENCES [dbo].[VENUES] ([ID]);
END