IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.VENUE_AMENITIES', N'U') AND name = N'IX_VENUE_AMENITIES_VENUE_ID_IS_AVAILABLE')
BEGIN
    CREATE INDEX [IX_VENUE_AMENITIES_VENUE_ID_IS_AVAILABLE] ON [dbo].[VENUE_AMENITIES] ([VENUE_ID], [IS_AVAILABLE]);
END