IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_HALLS_VENUES_VENUE_ID' AND parent_object_id = OBJECT_ID(N'dbo.HALLS'))
BEGIN
    ALTER TABLE [dbo].[HALLS] ADD CONSTRAINT [FK_HALLS_VENUES_VENUE_ID] FOREIGN KEY ([VENUE_ID]) REFERENCES [dbo].[VENUES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SEATS_HALLS_HALL_ID' AND parent_object_id = OBJECT_ID(N'dbo.SEATS'))
BEGIN
    ALTER TABLE [dbo].[SEATS] ADD CONSTRAINT [FK_SEATS_HALLS_HALL_ID] FOREIGN KEY ([HALL_ID]) REFERENCES [dbo].[HALLS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_VENUE_AMENITIES_VENUES_VENUE_ID' AND parent_object_id = OBJECT_ID(N'dbo.VENUE_AMENITIES'))
BEGIN
    ALTER TABLE [dbo].[VENUE_AMENITIES] ADD CONSTRAINT [FK_VENUE_AMENITIES_VENUES_VENUE_ID] FOREIGN KEY ([VENUE_ID]) REFERENCES [dbo].[VENUES] ([ID]);
END