IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_VENUE_AMENITIES_VENUES_VENUE_ID' AND parent_object_id = OBJECT_ID(N'dbo.VENUE_AMENITIES'))
BEGIN
    ALTER TABLE [dbo].[VENUE_AMENITIES] ADD CONSTRAINT [FK_VENUE_AMENITIES_VENUES_VENUE_ID] FOREIGN KEY ([VENUE_ID]) REFERENCES [dbo].[VENUES] ([ID]);
END