// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.IdentityModule.Domain.Entities;
using QuickCode.BirBilet.IdentityModule.Application.Dtos.TopicWorkflow;
using System.Threading.Tasks;
using QuickCode.BirBilet.IdentityModule.Domain.Enums;

namespace QuickCode.BirBilet.IdentityModule.Application.Interfaces.Repositories
{
    public partial interface ITopicWorkflowRepository : IBaseRepository<TopicWorkflowDto>
    {
        Task<RepoResponse<TopicWorkflowDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetWorkflowsResponseDto>>> GetWorkflowsAsync(string topicWorkflowKafkaEventsTopicName);
        Task<RepoResponse<List<GetWorkflows2ResponseDto>>> GetWorkflows2Async(string topicWorkflowKafkaEventsTopicName);
        Task<RepoResponse<List<GetTopicWorkflowsResponseDto>>> GetTopicWorkflowsAsync(string kafkaEventsTopicName, HttpMethodType apiMethodDefinitionsHttpMethod);
    }
}