// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.IdentityModule.Domain.Entities;
using QuickCode.BirBilet.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.IdentityModule.Application.Dtos.PortalPageAccessGrant;
using QuickCode.BirBilet.IdentityModule.Application.Mappings;
using QuickCode.BirBilet.IdentityModule.Persistence.Sql;
using QuickCode.BirBilet.IdentityModule.Domain.Enums;

namespace QuickCode.BirBilet.IdentityModule.Persistence.Repositories
{
    public partial class PortalPageAccessGrantRepository : BaseRepository, IPortalPageAccessGrantRepository
    {
        public async Task<RepoResponse<List<GetPortalPageAccessGrantsResponseDto>>> GetPortalPageAccessGrantsAsync(string portalPageAccessGrantPermissionGroupName)
        {
            return await ExecuteWithExceptionHandling(PortalPageAccessGrantCrudSqlBindings.OperationNames.GetPortalPageAccessGrants, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageAccessGrant.Query.GetPortalPageAccessGrants);
                var parameters = new
                {
                    PRM_PortalPageAccessGrant_PermissionGroupName = portalPageAccessGrantPermissionGroupName
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetPortalPageAccessGrantsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PortalPageAccessGrant");
            });
        }

        public async Task<RepoResponse<List<GetPortalPageAccessGrantResponseDto>>> GetPortalPageAccessGrantAsync(string portalPageAccessGrantPermissionGroupName, string portalPageAccessGrantPortalPageDefinitionKey, PageActionType portalPageAccessGrantPageAction)
        {
            return await ExecuteWithExceptionHandling(PortalPageAccessGrantCrudSqlBindings.OperationNames.GetPortalPageAccessGrant, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageAccessGrant.Query.GetPortalPageAccessGrant);
                var parameters = new
                {
                    PRM_PortalPageAccessGrant_PortalPageDefinitionKey = portalPageAccessGrantPortalPageDefinitionKey,
                    PRM_PortalPageAccessGrant_PermissionGroupName = portalPageAccessGrantPermissionGroupName,
                    PRM_PortalPageAccessGrant_PageAction = portalPageAccessGrantPageAction
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetPortalPageAccessGrantResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PortalPageAccessGrant");
            });
        }
    }
}