-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[PRICE_HISTORIES]
SET
    [PRICING_ID] = @PRM_PRICE_HISTORY_PRICING_ID,
    [OLD_PRICE] = @PRM_PRICE_HISTORY_OLD_PRICE,
    [NEW_PRICE] = @PRM_PRICE_HISTORY_NEW_PRICE,
    [CHANGED_DATE] = @PRM_PRICE_HISTORY_CHANGED_DATE,
    [CHANGE_REASON] = @PRM_PRICE_HISTORY_CHANGE_REASON
WHERE
    [ID] = @PRM_PRICE_HISTORY_ID
    AND [IsDeleted] = 0;