-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [PRICING_ID],
    [OLD_PRICE],
    [NEW_PRICE],
    [CHANGED_DATE],
    [CHANGE_REASON]
FROM [dbo].[PRICE_HISTORIES]
WHERE
    [ID] = @PRM_PRICE_HISTORY_ID
    AND [IsDeleted] = 0;