// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.VenueManagementModule.Domain.Entities;
using QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Venue;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Application.Services.Venue
{
    public partial class VenueService : IVenueService
    {
        private readonly ILogger<VenueService> _logger;
        private readonly IVenueRepository _repository;
        public VenueService(ILogger<VenueService> logger, IVenueRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<VenueDto>> InsertAsync(VenueDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(VenueDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, VenueDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<VenueDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<VenueDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetActiveAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByCityResponseDto>>> GetByCityAsync(string venueCity, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByCityAsync(venueCity, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByTypeResponseDto>>> GetByTypeAsync(VenueType venueVenueType, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByTypeAsync(venueVenueType, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<SearchByNameResponseDto>>> SearchByNameAsync(string venueName, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.SearchByNameAsync(venueName, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetWithContactResponseDto>>> GetWithContactAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetWithContactAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> DeactivateAsync(int venueId, DeactivateRequestDto updateRequest)
        {
            var returnValue = await _repository.DeactivateAsync(venueId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> UpdateContactAsync(int venueId, UpdateContactRequestDto updateRequest)
        {
            var returnValue = await _repository.UpdateContactAsync(venueId, updateRequest);
            return returnValue.ToResponse();
        }
    }
}