-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[VENUE_AMENITIES]
SET
    [VENUE_ID] = @PRM_VENUE_AMENITY_VENUE_ID,
    [AMENITY_NAME] = @PRM_VENUE_AMENITY_AMENITY_NAME,
    [DESCRIPTION] = @PRM_VENUE_AMENITY_DESCRIPTION,
    [IS_AVAILABLE] = @PRM_VENUE_AMENITY_IS_AVAILABLE
WHERE
    [ID] = @PRM_VENUE_AMENITY_ID
    AND [IsDeleted] = 0;