-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [VENUE_ID],
    [AMENITY_NAME],
    [DESCRIPTION],
    [IS_AVAILABLE]
FROM [dbo].[VENUE_AMENITIES]
WHERE
    [ID] = @PRM_VENUE_AMENITY_ID
    AND [IsDeleted] = 0;