-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 COUNT(*) AS TOTAL_ITEMS,
	SUM(BI.[PRICE]) AS TOTAL_PRICE 
FROM [BOOKING_ITEMS] BI 
WHERE BI.[IsDeleted] = 0 
	AND BI.[BOOKING_ID] = @PRM_BOOKING_ITEM_BOOKING_ID 