// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirBilet.TicketingModule.Application.Dtos.PriceHistory;

namespace QuickCode.BirBilet.TicketingModule.Persistence.Repositories;
internal static class PriceHistoryCrudSqlBindings
{
    public const string StoreTableName = "PRICE_HISTORIES";
    public const string ParameterNamePrefix = "PRICE_HISTORY";
    public const string IdParameterName = "PRM_PRICE_HISTORY_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string GetByPricing = "GetByPricing";
        public const string GetRecentChanges = "GetRecentChanges";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("PRICING_ID", nameof(PriceHistoryDto.PricingId)),
        ("OLD_PRICE", nameof(PriceHistoryDto.OldPrice)),
        ("NEW_PRICE", nameof(PriceHistoryDto.NewPrice)),
        ("CHANGED_DATE", nameof(PriceHistoryDto.ChangedDate)),
        ("CHANGE_REASON", nameof(PriceHistoryDto.ChangeReason))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("PRICING_ID", nameof(PriceHistoryDto.PricingId)),
        ("OLD_PRICE", nameof(PriceHistoryDto.OldPrice)),
        ("NEW_PRICE", nameof(PriceHistoryDto.NewPrice)),
        ("CHANGED_DATE", nameof(PriceHistoryDto.ChangedDate)),
        ("CHANGE_REASON", nameof(PriceHistoryDto.ChangeReason)),
        ("ID", nameof(PriceHistoryDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(PriceHistoryDto.Id))
    };
}