// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.TicketingModule.Domain.Entities;
using QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.PriceHistory;
using QuickCode.BirBilet.TicketingModule.Application.Mappings;
using QuickCode.BirBilet.TicketingModule.Persistence.Sql;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Persistence.Repositories
{
    public partial class PriceHistoryRepository : BaseRepository, IPriceHistoryRepository
    {
        public async Task<RepoResponse<List<GetByPricingResponseDto>>> GetByPricingAsync(int priceHistoryPricingId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(PriceHistoryCrudSqlBindings.OperationNames.GetByPricing, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByPricingResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.PriceHistory.Query.GetByPricing);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PRICE_HISTORY_PRICING_ID = priceHistoryPricingId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByPricingResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in PriceHistory");
                }
            });
        }

        public async Task<RepoResponse<List<GetRecentChangesResponseDto>>> GetRecentChangesAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(PriceHistoryCrudSqlBindings.OperationNames.GetRecentChanges, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetRecentChangesResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.PriceHistory.Query.GetRecentChanges);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetRecentChangesResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in PriceHistory");
                }
            });
        }
    }
}