// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirBilet.Portal.Models;
using QuickCode.BirBilet.Portal.Models.VenueManagementModule;
using QuickCode.BirBilet.Portal.Helpers;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.BirBilet.Infrastructure.Integration.Nswag.Clients.IdentityModuleApi.Contracts;
using VenueManagementModuleContracts = QuickCode.BirBilet.Infrastructure.Integration.Nswag.Clients.VenueManagementModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.BirBilet.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.BirBilet.Portal.Controllers.VenueManagementModule
{
    [Permission("VenueManagementModuleVenues")]
    [Area("VenueManagementModule")]
    [Route("VenueManagementModuleVenues")]
    public partial class VenuesController : BaseController
    {
        private readonly VenueManagementModuleContracts.IVenuesClient pageClient;
        public VenuesController(VenueManagementModuleContracts.IVenuesClient pageClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(VenueData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(VenueData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.VenuesInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(VenueData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.VenuesUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(VenueData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.VenuesDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(VenueData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(VenueData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(VenueData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(VenueData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<VenueData> PrepareModel()
        {
            var model = GetModel<VenueData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<VenueData> PrepareModel(VenueData model)
        {
            model.NumberOfRecord = await pageClient.VenuesCountAsync();
            model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
            model.List = (await pageClient.VenuesListAsync(model.CurrentPage, PageSize)).ToList();
            return model;
        }
    }
}