// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Hall;
using HallEntity = QuickCode.BirBilet.VenueManagementModule.Domain.Entities.Hall;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Application.Mappings
{
    public static class HallMappings
    {
        public static List<HallDto> ToDto(this IEnumerable<HallEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static HallDto ToDto(this HallEntity model)
        {
            return new HallDto
            {
                Id = model.Id,
                VenueId = model.VenueId,
                HallName = model.HallName,
                HallNumber = model.HallNumber,
                Capacity = model.Capacity,
                TotalRows = model.TotalRows,
                TotalColumns = model.TotalColumns,
                Status = model.Status,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static HallEntity ToEntity(this HallDto model)
        {
            return new HallEntity
            {
                Id = model.Id,
                VenueId = model.VenueId,
                HallName = model.HallName,
                HallNumber = model.HallNumber,
                Capacity = model.Capacity,
                TotalRows = model.TotalRows,
                TotalColumns = model.TotalColumns,
                Status = model.Status,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}