-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[SCHEDULE_HISTORIES] (
    [SCHEDULE_ID],
    [PREVIOUS_STATUS],
    [NEW_STATUS],
    [CHANGED_DATE],
    [CHANGE_REASON]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_SCHEDULE_HISTORY_SCHEDULE_ID,
    @PRM_SCHEDULE_HISTORY_PREVIOUS_STATUS,
    @PRM_SCHEDULE_HISTORY_NEW_STATUS,
    @PRM_SCHEDULE_HISTORY_CHANGED_DATE,
    @PRM_SCHEDULE_HISTORY_CHANGE_REASON
    );