-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[SCHEDULE_HISTORIES]
SET
    [SCHEDULE_ID] = @PRM_SCHEDULE_HISTORY_SCHEDULE_ID,
    [PREVIOUS_STATUS] = @PRM_SCHEDULE_HISTORY_PREVIOUS_STATUS,
    [NEW_STATUS] = @PRM_SCHEDULE_HISTORY_NEW_STATUS,
    [CHANGED_DATE] = @PRM_SCHEDULE_HISTORY_CHANGED_DATE,
    [CHANGE_REASON] = @PRM_SCHEDULE_HISTORY_CHANGE_REASON
WHERE
    [ID] = @PRM_SCHEDULE_HISTORY_ID
    AND [IsDeleted] = 0;