-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [SCHEDULE_ID],
    [PREVIOUS_STATUS],
    [NEW_STATUS],
    [CHANGED_DATE],
    [CHANGE_REASON]
FROM [dbo].[SCHEDULE_HISTORIES]
WHERE
    [ID] = @PRM_SCHEDULE_HISTORY_ID
    AND [IsDeleted] = 0;