-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [HALL_ID],
    [SEAT_NUMBER],
    [ROW_NUMBER],
    [COLUMN_NUMBER],
    [CATEGORY],
    [STATUS],
    [IS_ACTIVE]
FROM [dbo].[SEATS]
WHERE
    [ID] = @PRM_SEAT_ID
    AND [IsDeleted] = 0;