-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT VA.[ID], VA.[AMENITY_NAME], VA.[DESCRIPTION] 
FROM [VENUE_AMENITIES] VA 
WHERE VA.[IsDeleted] = 0 
	AND VA.[VENUE_ID] = @PRM_VENUE_AMENITY_VENUE_ID 
	AND VA.[IS_AVAILABLE] = 1 
ORDER BY VA.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 