// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirBilet.VenueManagementModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class VenueAmenity
    {
        public static class Query
        {
            private const string _prefix = "VenueManagementModule.VenueAmenity.Query";
            private const string _sqlScriptStem = "VenueAmenity";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetByVenue => ResourceKey($"{_sqlScriptStem}.GetByVenue.g.sql");
            public static string GetAvailable => ResourceKey($"{_sqlScriptStem}.GetAvailable.g.sql");
        }
    }
}