// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Application.Dtos.PriceHistory
{
    public record GetByPricingResponseDto
    {
        public int Id { get; init; }
        public decimal OldPrice { get; init; }
        public decimal NewPrice { get; init; }
        public DateTime ChangedDate { get; init; }
        public string ChangeReason { get; init; }
    }
}