-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 COUNT(*) AS TICKETS_SOLD,
	SUM(T.[PRICE]) AS DAILY_REVENUE 
FROM [TICKETS] T 
WHERE T.[IsDeleted] = 0 
	AND T.[PURCHASE_DATE] > DATEADD(DAY, -1,
	GETDATE()) 