-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT T.[ID], T.[TICKET_NUMBER], T.[SCHEDULE_ID], T.[CUSTOMER_ID], T.[PURCHASE_DATE] 
FROM [TICKETS] T 
WHERE T.[IsDeleted] = 0 
	AND T.[STATUS] = 'RESERVED' 
ORDER BY T.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 