-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 [SCHEDULE_ID], COUNT(*) AS TICKETS_SOLD,
	SUM(T.[PRICE]) AS TOTAL_REVENUE 
FROM [TICKETS] T 
WHERE T.[IsDeleted] = 0 
	AND T.[SCHEDULE_ID] = @PRM_TICKET_SCHEDULE_ID 
GROUP BY T.[SCHEDULE_ID] 
ORDER BY T.[SCHEDULE_ID] 