-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT H.[ID], H.[VENUE_ID], H.[HALL_NAME], H.[CAPACITY], H.[STATUS] 
FROM [HALLS] H 
WHERE H.[IsDeleted] = 0 
	AND H.[IS_ACTIVE] = 1 
ORDER BY H.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 