// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QcEntity = global::QuickCode.BirBilet.EventManagementModule.Domain.Entities;
using QuickCode.BirBilet.EventManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.EventType;
using QuickCode.BirBilet.EventManagementModule.Application.Mappings;
using QuickCode.BirBilet.EventManagementModule.Persistence.Sql;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Persistence.Repositories
{
    public partial class EventTypeRepository : BaseRepository, IEventTypeRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public EventTypeRepository(ILogger<EventTypeRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "EventType")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<EventTypeDto>> InsertAsync(EventTypeDto value)
        {
            return await ExecuteWithExceptionHandling(EventTypeCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.EventType.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(EventTypeCrudSqlBindings.ParameterNamePrefix, value, EventTypeCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.EventType>(sql, p);
                return new RepoResponse<EventTypeDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(EventTypeDto value)
        {
            return await ExecuteWithExceptionHandling(EventTypeCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.EventType.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(EventTypeCrudSqlBindings.ParameterNamePrefix, value, EventTypeCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(EventTypeDto value)
        {
            return await ExecuteWithExceptionHandling(EventTypeCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.EventType.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(EventTypeCrudSqlBindings.ParameterNamePrefix, value, EventTypeCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<EventTypeDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(EventTypeCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.EventType.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(EventTypeCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.EventType>(sql, p);
                return row == null ? CreateNotFoundResponse<EventTypeDto>("Not found in EventType") : new RepoResponse<EventTypeDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<EventTypeDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(EventTypeCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<EventTypeDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.EventType.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.EventType>(sql, p);
                return new RepoResponse<List<EventTypeDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(EventTypeCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.EventType.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}