// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirBilet.IdentityModule.Domain;
using QuickCode.BirBilet.Domain.Shared.Abstractions;
using QuickCode.BirBilet.Domain.Shared.Entities;

namespace QuickCode.BirBilet.IdentityModule.Domain.Entities;

[Table("TopicWorkflows")]
public partial class TopicWorkflow : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("Id")]
	public int Id { get; set; }
	
	[Column("KafkaEventsTopicName")]
	[StringLength(1000)]
	public string KafkaEventsTopicName { get; set; }
	
	[Column("WorkflowContent")]
	[StringLength(int.MaxValue)]
	public string WorkflowContent { get; set; }
	
	[ForeignKey("KafkaEventsTopicName")]
	[InverseProperty(nameof(KafkaEvent.TopicWorkflows))]
	public virtual KafkaEvent KafkaEvent { get; set; } = null!;
}

