-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[EVENT_TYPES] (
    [TYPE_NAME],
    [DESCRIPTION],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_EVENT_TYPE_TYPE_NAME,
    @PRM_EVENT_TYPE_DESCRIPTION,
    @PRM_EVENT_TYPE_IS_ACTIVE
    );