// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirBilet.EventManagementModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class EventItem
    {
        public static class Query
        {
            private const string _prefix = "EventManagementModule.EventItem.Query";
            private const string _sqlScriptStem = "EventItem";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetActive => ResourceKey($"{_sqlScriptStem}.GetActive.g.sql");
            public static string GetByType => ResourceKey($"{_sqlScriptStem}.GetByType.g.sql");
            public static string GetPublished => ResourceKey($"{_sqlScriptStem}.GetPublished.g.sql");
            public static string SearchByName => ResourceKey($"{_sqlScriptStem}.SearchByName.g.sql");
            public static string GetRecent => ResourceKey($"{_sqlScriptStem}.GetRecent.g.sql");
            public static string GetUpcoming => ResourceKey($"{_sqlScriptStem}.GetUpcoming.g.sql");
            public static string GetTotalByType => ResourceKey($"{_sqlScriptStem}.GetTotalByType.g.sql");
        }
    }
}