// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.SeatCategory;

namespace QuickCode.BirBilet.VenueManagementModule.Persistence.Repositories;
internal static class SeatCategoryCrudSqlBindings
{
    public const string StoreTableName = "SEAT_CATEGORIES";
    public const string ParameterNamePrefix = "SEAT_CATEGORY";
    public const string IdParameterName = "PRM_SEAT_CATEGORY_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CATEGORY_NAME", nameof(SeatCategoryDto.CategoryName)),
        ("DESCRIPTION", nameof(SeatCategoryDto.Description)),
        ("IS_ACTIVE", nameof(SeatCategoryDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CATEGORY_NAME", nameof(SeatCategoryDto.CategoryName)),
        ("DESCRIPTION", nameof(SeatCategoryDto.Description)),
        ("IS_ACTIVE", nameof(SeatCategoryDto.IsActive)),
        ("ID", nameof(SeatCategoryDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(SeatCategoryDto.Id))
    };
}