-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT P.[ID], P.[SEAT_CATEGORY], P.[PRICE_TYPE], P.[BASE_PRICE], P.[FINAL_PRICE], P.[IS_ACTIVE] 
FROM [PRICINGS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[SCHEDULE_ID] = @PRM_PRICING_SCHEDULE_ID 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 