// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirBilet.TicketingModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Pricing
    {
        public static class Query
        {
            private const string _prefix = "TicketingModule.Pricing.Query";
            private const string _sqlScriptStem = "Pricing";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetBySchedule => ResourceKey($"{_sqlScriptStem}.GetBySchedule.g.sql");
            public static string GetActive => ResourceKey($"{_sqlScriptStem}.GetActive.g.sql");
            public static string GetByCategory => ResourceKey($"{_sqlScriptStem}.GetByCategory.g.sql");
            public static string GetEarlyBird => ResourceKey($"{_sqlScriptStem}.GetEarlyBird.g.sql");
            public static string GetPremiumPricing => ResourceKey($"{_sqlScriptStem}.GetPremiumPricing.g.sql");
            public static string GetPricingSummary => ResourceKey($"{_sqlScriptStem}.GetPricingSummary.g.sql");
        }
    }
}