-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT S.[ID], S.[SCHEDULE_DATE], S.[START_TIME], S.[VENUE_ID], S.[HALL_ID], S.[AVAILABLE_SEATS], S.[STATUS] 
FROM [SCHEDULES] S 
WHERE S.[IsDeleted] = 0 
	AND S.[EVENT_ID] = @PRM_SCHEDULE_EVENT_ID 
ORDER BY S.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 