-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [EVENT_ID],
    [VENUE_ID],
    [HALL_ID],
    [SCHEDULE_DATE],
    [START_TIME],
    [END_TIME],
    [STATUS],
    [TOTAL_SEATS],
    [AVAILABLE_SEATS],
    [CREATED_DATE]
FROM [dbo].[SCHEDULES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;