// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirBilet.EventManagementModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class EventItem
    {
        public static class Command
        {
            private const string _prefix = "EventManagementModule.EventItem.Command";
            private const string _sqlScriptStem = "EventItem";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string Publish => ResourceKey($"{_sqlScriptStem}.Publish.g.sql");
            public static string Cancel => ResourceKey($"{_sqlScriptStem}.Cancel.g.sql");
            public static string MarkCompleted => ResourceKey($"{_sqlScriptStem}.MarkCompleted.g.sql");
            public static string Deactivate => ResourceKey($"{_sqlScriptStem}.Deactivate.g.sql");
        }
    }
}