-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[TICKETS] (
    [TICKET_NUMBER],
    [SCHEDULE_ID],
    [SEAT_ID],
    [PRICE],
    [STATUS],
    [CUSTOMER_ID],
    [PURCHASE_DATE],
    [REDEMPTION_DATE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_TICKET_TICKET_NUMBER,
    @PRM_TICKET_SCHEDULE_ID,
    @PRM_TICKET_SEAT_ID,
    @PRM_TICKET_PRICE,
    @PRM_TICKET_STATUS,
    @PRM_TICKET_CUSTOMER_ID,
    @PRM_TICKET_PURCHASE_DATE,
    @PRM_TICKET_REDEMPTION_DATE,
    @PRM_TICKET_CREATED_DATE
    );