-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[TICKETS]
SET
    [TICKET_NUMBER] = @PRM_TICKET_TICKET_NUMBER,
    [SCHEDULE_ID] = @PRM_TICKET_SCHEDULE_ID,
    [SEAT_ID] = @PRM_TICKET_SEAT_ID,
    [PRICE] = @PRM_TICKET_PRICE,
    [STATUS] = @PRM_TICKET_STATUS,
    [CUSTOMER_ID] = @PRM_TICKET_CUSTOMER_ID,
    [PURCHASE_DATE] = @PRM_TICKET_PURCHASE_DATE,
    [REDEMPTION_DATE] = @PRM_TICKET_REDEMPTION_DATE,
    [CREATED_DATE] = @PRM_TICKET_CREATED_DATE
WHERE
    [ID] = @PRM_TICKET_ID
    AND [IsDeleted] = 0;