// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.EventManagementModule.Domain.Entities;
using QuickCode.BirBilet.EventManagementModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.Schedule;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Application.Services.Schedule
{
    public partial class ScheduleService : IScheduleService
    {
        private readonly ILogger<ScheduleService> _logger;
        private readonly IScheduleRepository _repository;
        public ScheduleService(ILogger<ScheduleService> logger, IScheduleRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<ScheduleDto>> InsertAsync(ScheduleDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(ScheduleDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, ScheduleDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<ScheduleDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<ScheduleDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByEventResponseDto>>> GetByEventAsync(int scheduleEventId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByEventAsync(scheduleEventId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByVenueResponseDto>>> GetByVenueAsync(int scheduleVenueId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByVenueAsync(scheduleVenueId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByDateRangeResponseDto>>> GetByDateRangeAsync(DateTime scheduleScheduleDateFrom, DateTime scheduleScheduleDateTo, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByDateRangeAsync(scheduleScheduleDateFrom, scheduleScheduleDateTo, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetAvailableResponseDto>>> GetAvailableAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetAvailableAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetUpcomingSchedulesResponseDto>>> GetUpcomingSchedulesAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetUpcomingSchedulesAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetSoldOutResponseDto>>> GetSoldOutAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetSoldOutAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetTodaySchedulesResponseDto>>> GetTodaySchedulesAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetTodaySchedulesAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetScheduleSummaryResponseDto>> GetScheduleSummaryAsync(int scheduleEventId)
        {
            var returnValue = await _repository.GetScheduleSummaryAsync(scheduleEventId);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> UpdateAvailableSeatsAsync(int scheduleId, UpdateAvailableSeatsRequestDto updateRequest)
        {
            var returnValue = await _repository.UpdateAvailableSeatsAsync(scheduleId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> MarkSoldOutAsync(int scheduleId, MarkSoldOutRequestDto updateRequest)
        {
            var returnValue = await _repository.MarkSoldOutAsync(scheduleId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> CancelScheduleAsync(int scheduleId, CancelScheduleRequestDto updateRequest)
        {
            var returnValue = await _repository.CancelScheduleAsync(scheduleId, updateRequest);
            return returnValue.ToResponse();
        }
    }
}