// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.TicketingModule.Domain.Entities;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.PaymentRecord;
using System.Threading.Tasks;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories
{
    public partial interface IPaymentRecordRepository : IBaseRepository<PaymentRecordDto>
    {
        Task<RepoResponse<PaymentRecordDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByBookingResponseDto>>> GetByBookingAsync(int paymentRecordBookingId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByDateRangeResponseDto>>> GetByDateRangeAsync(DateTime paymentRecordPaymentDateFrom, DateTime paymentRecordPaymentDateTo, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetDailyPaymentsResponseDto>> GetDailyPaymentsAsync();
        Task<RepoResponse<GetMonthlyPaymentsResponseDto>> GetMonthlyPaymentsAsync();
    }
}