// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.TicketingModule.Domain.Entities;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.Ticket;
using System.Threading.Tasks;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories
{
    public partial interface ITicketRepository : IBaseRepository<TicketDto>
    {
        Task<RepoResponse<TicketDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByScheduleResponseDto>>> GetByScheduleAsync(int ticketScheduleId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetAvailableResponseDto>>> GetAvailableAsync(int ticketScheduleId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByCustomerResponseDto>>> GetByCustomerAsync(int ticketCustomerId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetSoldResponseDto>>> GetSoldAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetRedeemedResponseDto>>> GetRedeemedAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetReservedResponseDto>>> GetReservedAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetDailySalesResponseDto>> GetDailySalesAsync();
        Task<RepoResponse<GetMonthlyRevenueResponseDto>> GetMonthlyRevenueAsync();
        Task<RepoResponse<GetRevenueByScheduleResponseDto>> GetRevenueByScheduleAsync(int ticketScheduleId);
        Task<RepoResponse<int>> MarkSoldAsync(int ticketId, MarkSoldRequestDto updateRequest);
        Task<RepoResponse<int>> MarkRedeemedAsync(int ticketId, MarkRedeemedRequestDto updateRequest);
        Task<RepoResponse<int>> CancelAsync(int ticketId, CancelRequestDto updateRequest);
        Task<RepoResponse<int>> ReserveAsync(int ticketId, ReserveRequestDto updateRequest);
    }
}