// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirBilet.TicketingModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Booking
    {
        public static class Command
        {
            private const string _prefix = "TicketingModule.Booking.Command";
            private const string _sqlScriptStem = "Booking";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string Confirm => ResourceKey($"{_sqlScriptStem}.Confirm.g.sql");
            public static string MarkExpired => ResourceKey($"{_sqlScriptStem}.MarkExpired.g.sql");
            public static string Cancel => ResourceKey($"{_sqlScriptStem}.Cancel.g.sql");
            public static string Complete => ResourceKey($"{_sqlScriptStem}.Complete.g.sql");
        }
    }
}