// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Web.Controllers;
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.Schedule;
using QuickCode.BirBilet.EventManagementModule.Application.Services.Schedule;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Api.Controllers
{
    public partial class SchedulesController : QuickCodeBaseApiController
    {
        private readonly IScheduleService service;
        private readonly ILogger<SchedulesController> logger;
        private readonly IServiceProvider serviceProvider;
        public SchedulesController(IScheduleService service, IServiceProvider serviceProvider, ILogger<SchedulesController> logger)
        {
            this.service = service;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<ScheduleDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await service.ListAsync(page, size);
            if (HandleResponseError(response, logger, "Schedule", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await service.TotalItemCountAsync();
            if (HandleResponseError(response, logger, "Schedule") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ScheduleDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await service.GetItemAsync(id);
            if (HandleResponseError(response, logger, "Schedule", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(ScheduleDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(ScheduleDto model)
        {
            var response = await service.InsertAsync(model);
            if (HandleResponseError(response, logger, "Schedule") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, ScheduleDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await service.UpdateAsync(id, model);
            if (HandleResponseError(response, logger, "Schedule", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await service.DeleteItemAsync(id);
            if (HandleResponseError(response, logger, "Schedule", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-event/{scheduleEventId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByEventResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByEventAsync(int scheduleEventId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetByEventAsync(scheduleEventId, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Schedule", $"ScheduleEventId: '{scheduleEventId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-venue/{scheduleVenueId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByVenueResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByVenueAsync(int scheduleVenueId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetByVenueAsync(scheduleVenueId, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Schedule", $"ScheduleVenueId: '{scheduleVenueId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-date-range/{scheduleScheduleDateFrom:DateTime}/{scheduleScheduleDateTo:DateTime}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByDateRangeResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByDateRangeAsync(DateTime scheduleScheduleDateFrom, DateTime scheduleScheduleDateTo, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetByDateRangeAsync(scheduleScheduleDateFrom, scheduleScheduleDateTo, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Schedule", $"ScheduleScheduleDateFrom: '{scheduleScheduleDateFrom}', ScheduleScheduleDateTo: '{scheduleScheduleDateTo}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-available")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetAvailableResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetAvailableAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetAvailableAsync(pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Schedule", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-upcoming-schedules")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetUpcomingSchedulesResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetUpcomingSchedulesAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetUpcomingSchedulesAsync(pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Schedule", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-sold-out")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetSoldOutResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetSoldOutAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetSoldOutAsync(pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Schedule", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-today-schedules")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetTodaySchedulesResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetTodaySchedulesAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetTodaySchedulesAsync(pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Schedule", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-schedule-summary/{scheduleEventId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetScheduleSummaryResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetScheduleSummaryAsync(int scheduleEventId)
        {
            var response = await service.GetScheduleSummaryAsync(scheduleEventId);
            if (HandleResponseError(response, logger, "Schedule", $"ScheduleEventId: '{scheduleEventId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("update-available-seats/{scheduleId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAvailableSeatsAsync(int scheduleId, [FromBody] UpdateAvailableSeatsRequestDto updateRequest)
        {
            var response = await service.UpdateAvailableSeatsAsync(scheduleId, updateRequest);
            if (HandleResponseError(response, logger, "Schedule", $"ScheduleId: '{scheduleId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("mark-sold-out/{scheduleId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> MarkSoldOutAsync(int scheduleId, [FromBody] MarkSoldOutRequestDto updateRequest)
        {
            var response = await service.MarkSoldOutAsync(scheduleId, updateRequest);
            if (HandleResponseError(response, logger, "Schedule", $"ScheduleId: '{scheduleId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("cancel-schedule/{scheduleId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CancelScheduleAsync(int scheduleId, [FromBody] CancelScheduleRequestDto updateRequest)
        {
            var response = await service.CancelScheduleAsync(scheduleId, updateRequest);
            if (HandleResponseError(response, logger, "Schedule", $"ScheduleId: '{scheduleId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}