// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.IdentityModule.Domain.Entities;
using QuickCode.BirBilet.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.IdentityModule.Application.Dtos.ApiMethodAccessGrant;
using QuickCode.BirBilet.IdentityModule.Application.Mappings;
using QuickCode.BirBilet.IdentityModule.Persistence.Sql;
using QuickCode.BirBilet.IdentityModule.Domain.Enums;

namespace QuickCode.BirBilet.IdentityModule.Persistence.Repositories
{
    public partial class ApiMethodAccessGrantRepository : BaseRepository, IApiMethodAccessGrantRepository
    {
        public async Task<RepoResponse<List<GetApiMethodAccessGrantNamesResponseDto>>> GetApiMethodAccessGrantNamesAsync(string apiMethodAccessGrantPermissionGroupName)
        {
            return await ExecuteWithExceptionHandling(ApiMethodAccessGrantCrudSqlBindings.OperationNames.GetApiMethodAccessGrantNames, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodAccessGrant.Query.GetApiMethodAccessGrantNames);
                var parameters = new
                {
                    PRM_ApiMethodAccessGrant_PermissionGroupName = apiMethodAccessGrantPermissionGroupName
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetApiMethodAccessGrantNamesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodAccessGrant");
            });
        }
    }
}