-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT ET.[ID], ET.[TYPE_NAME], ET.[DESCRIPTION] 
FROM [EVENT_TYPES] ET 
WHERE ET.[IsDeleted] = 0 
	AND ET.[IS_ACTIVE] = 1 
ORDER BY ET.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 