-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[VENUES]
SET
    [NAME] = @PRM_VENUE_NAME,
    [ADDRESS] = @PRM_VENUE_ADDRESS,
    [CITY] = @PRM_VENUE_CITY,
    [COUNTRY] = @PRM_VENUE_COUNTRY,
    [VENUE_TYPE] = @PRM_VENUE_VENUE_TYPE,
    [PHONE] = @PRM_VENUE_PHONE,
    [EMAIL] = @PRM_VENUE_EMAIL,
    [WEBSITE_URL] = @PRM_VENUE_WEBSITE_URL,
    [TOTAL_HALLS] = @PRM_VENUE_TOTAL_HALLS,
    [IS_ACTIVE] = @PRM_VENUE_IS_ACTIVE,
    [CREATED_DATE] = @PRM_VENUE_CREATED_DATE
WHERE
    [ID] = @PRM_VENUE_ID
    AND [IsDeleted] = 0;