-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[VENUES] (
    [NAME],
    [ADDRESS],
    [CITY],
    [COUNTRY],
    [VENUE_TYPE],
    [PHONE],
    [EMAIL],
    [WEBSITE_URL],
    [TOTAL_HALLS],
    [IS_ACTIVE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_VENUE_NAME,
    @PRM_VENUE_ADDRESS,
    @PRM_VENUE_CITY,
    @PRM_VENUE_COUNTRY,
    @PRM_VENUE_VENUE_TYPE,
    @PRM_VENUE_PHONE,
    @PRM_VENUE_EMAIL,
    @PRM_VENUE_WEBSITE_URL,
    @PRM_VENUE_TOTAL_HALLS,
    @PRM_VENUE_IS_ACTIVE,
    @PRM_VENUE_CREATED_DATE
    );