// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.TicketingModule.Application.Services.Ticket;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.Ticket;
using QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.Infrastructure.Web.Helpers;
using QuickCode.BirBilet.Application.Contracts;

namespace QuickCode.BirBilet.TicketingModule.Application.Tests.Services.Ticket
{
    public class InsertTicketCommandTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<ITicketRepository> _repositoryMock;
        private readonly Mock<ILogger<TicketService>> _loggerMock;
        private readonly TicketService _service;
        public InsertTicketCommandTests()
        {
            _repositoryMock = new Mock<ITicketRepository>();
            _loggerMock = new Mock<ILogger<TicketService>>();
            _service = new TicketService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_Success_When_Valid_Request()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<TicketDto>("tr");
            var fakeResponse = new RepoResponse<TicketDto>(fakeDto, "Success");
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<TicketDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeDto, result.Value);
            _repositoryMock.Verify(r => r.InsertAsync(It.IsAny<TicketDto>()), Times.Once);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_NotFound_When_Repository_Returns_404()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<TicketDto>("tr");
            var fakeResponse = new RepoResponse<TicketDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<TicketDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.Null(result.Value);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}