// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.TicketingModule.Application.Services.Ticket;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.Ticket;
using QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.Infrastructure.Web.Helpers;
using QuickCode.BirBilet.Application.Contracts;

namespace QuickCode.BirBilet.TicketingModule.Application.Tests.Services.Ticket
{
    public class TicketTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<ITicketRepository> _repositoryMock;
        private readonly Mock<ILogger<TicketService>> _loggerMock;
        private readonly TicketService _service;
        public TicketTests()
        {
            _repositoryMock = new Mock<ITicketRepository>();
            _loggerMock = new Mock<ILogger<TicketService>>();
            _service = new TicketService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task GetItemAsync_Should_Return_Success_When_Item_Exists()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<TicketDto>("tr");
            var fakeResponse = new RepoResponse<TicketDto>(fakeDto, "Success");
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id)).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.GetItemAsync(fakeDto.Id);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeDto, result.Value);
            _repositoryMock.Verify(r => r.GetByPkAsync(fakeDto.Id), Times.Once);
        }

        [Fact]
        public async Task GetItemAsync_Should_Return_NotFound_When_Item_Does_Not_Exist()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<TicketDto>("tr");
            var fakeResponse = new RepoResponse<TicketDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id)).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.GetItemAsync(fakeDto.Id);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.Null(result.Value);
        }

        [Fact]
        public async Task ListAsync_Should_Return_Success_When_Valid_Request()
        {
            // Arrange
            var fakeList = TestDataGenerator.CreateFakes<TicketDto>("tr");
            var fakeResponse = new RepoResponse<List<TicketDto>>(fakeList, "Success");
            _repositoryMock.Setup(r => r.ListAsync(It.IsAny<int?>(), It.IsAny<int?>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.ListAsync(1, 10);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeList, result.Value);
            _repositoryMock.Verify(r => r.ListAsync(It.IsAny<int?>(), It.IsAny<int?>()), Times.Once);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}