// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.TicketingModule.Domain.Entities;
using QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.Ticket;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Application.Services.Ticket
{
    public partial class TicketService : ITicketService
    {
        private readonly ILogger<TicketService> _logger;
        private readonly ITicketRepository _repository;
        public TicketService(ILogger<TicketService> logger, ITicketRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<TicketDto>> InsertAsync(TicketDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(TicketDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, TicketDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<TicketDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<TicketDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByScheduleResponseDto>>> GetByScheduleAsync(int ticketScheduleId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByScheduleAsync(ticketScheduleId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetAvailableResponseDto>>> GetAvailableAsync(int ticketScheduleId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetAvailableAsync(ticketScheduleId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByCustomerResponseDto>>> GetByCustomerAsync(int ticketCustomerId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByCustomerAsync(ticketCustomerId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetSoldResponseDto>>> GetSoldAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetSoldAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetRedeemedResponseDto>>> GetRedeemedAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetRedeemedAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetReservedResponseDto>>> GetReservedAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetReservedAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetDailySalesResponseDto>> GetDailySalesAsync()
        {
            var returnValue = await _repository.GetDailySalesAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<GetMonthlyRevenueResponseDto>> GetMonthlyRevenueAsync()
        {
            var returnValue = await _repository.GetMonthlyRevenueAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<GetRevenueByScheduleResponseDto>> GetRevenueByScheduleAsync(int ticketScheduleId)
        {
            var returnValue = await _repository.GetRevenueByScheduleAsync(ticketScheduleId);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> MarkSoldAsync(int ticketId, MarkSoldRequestDto updateRequest)
        {
            var returnValue = await _repository.MarkSoldAsync(ticketId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> MarkRedeemedAsync(int ticketId, MarkRedeemedRequestDto updateRequest)
        {
            var returnValue = await _repository.MarkRedeemedAsync(ticketId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> CancelAsync(int ticketId, CancelRequestDto updateRequest)
        {
            var returnValue = await _repository.CancelAsync(ticketId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> ReserveAsync(int ticketId, ReserveRequestDto updateRequest)
        {
            var returnValue = await _repository.ReserveAsync(ticketId, updateRequest);
            return returnValue.ToResponse();
        }
    }
}