// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Seat
{
    public record GetAvailableByRowResponseDto
    {
        public int Id { get; init; }
        public string SeatNumber { get; init; }
        public int ColumnNumber { get; init; }
        public SeatCategoryKind Category { get; init; }
    }
}