// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirBilet.TicketingModule.Domain;
using QuickCode.BirBilet.Domain.Shared.Abstractions;
using QuickCode.BirBilet.Domain.Shared.Entities;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Domain.Entities;

[Table("BOOKINGS")]
public partial class Booking : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("BOOKING_NUMBER")]
	[StringLength(50)]
	public string BookingNumber { get; set; }
	
	[Column("SCHEDULE_ID")]
	public int ScheduleId { get; set; }
	
	[Column("CUSTOMER_ID")]
	public int CustomerId { get; set; }
	
	[Column("TOTAL_SEATS")]
	public int TotalSeats { get; set; }
	
	[Column("TOTAL_AMOUNT")]
	public decimal TotalAmount { get; set; }
	
	[Column("STATUS", TypeName = "nvarchar(50)")]
	public BookingStatus Status { get; set; }
	
	[Column("BOOKING_DATE")]
	public DateTime BookingDate { get; set; }
	
	[Column("EXPIRY_DATE")]
	public DateTime ExpiryDate { get; set; }
	
	[Column("CONFIRMATION_DATE")]
	public DateTime ConfirmationDate { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	
	[InverseProperty(nameof(BookingItem.Booking))]
	public virtual ICollection<BookingItem> BookingItems { get; } = new List<BookingItem>();

	[InverseProperty(nameof(PaymentRecord.Booking))]
	public virtual ICollection<PaymentRecord> PaymentRecords { get; } = new List<PaymentRecord>();
}

