// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirBilet.TicketingModule.Domain;
using QuickCode.BirBilet.Domain.Shared.Abstractions;
using QuickCode.BirBilet.Domain.Shared.Entities;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Domain.Entities;

[Table("PRICINGS")]
public partial class Pricing : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("SCHEDULE_ID")]
	public int ScheduleId { get; set; }
	
	[Column("SEAT_CATEGORY", TypeName = "nvarchar(50)")]
	public SeatCategory SeatCategory { get; set; }
	
	[Column("PRICE_TYPE", TypeName = "nvarchar(50)")]
	public PriceType PriceType { get; set; }
	
	[Column("BASE_PRICE")]
	public decimal BasePrice { get; set; }
	
	[Column("DISCOUNT_PERCENTAGE")]
	public decimal? DiscountPercentage { get; set; }
	
	[Column("FINAL_PRICE")]
	public decimal FinalPrice { get; set; }
	
	[Column("VALID_FROM")]
	public DateTime ValidFrom { get; set; }
	
	[Column("VALID_TO")]
	public DateTime ValidTo { get; set; }
	
	[Column("IS_ACTIVE")]
	public bool IsActive { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	
	[InverseProperty(nameof(PriceHistory.Pricing))]
	public virtual ICollection<PriceHistory> PriceHistories { get; } = new List<PriceHistory>();
}

