// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirBilet.TicketingModule.Domain;
using QuickCode.BirBilet.Domain.Shared.Abstractions;
using QuickCode.BirBilet.Domain.Shared.Entities;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Domain.Entities;

[Table("TICKETS")]
public partial class Ticket : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("TICKET_NUMBER")]
	[StringLength(50)]
	public string TicketNumber { get; set; }
	
	[Column("SCHEDULE_ID")]
	public int ScheduleId { get; set; }
	
	[Column("SEAT_ID")]
	public int SeatId { get; set; }
	
	[Column("PRICE")]
	public decimal Price { get; set; }
	
	[Column("STATUS", TypeName = "nvarchar(50)")]
	public TicketStatus Status { get; set; }
	
	[Column("CUSTOMER_ID")]
	public int CustomerId { get; set; }
	
	[Column("PURCHASE_DATE")]
	public DateTime PurchaseDate { get; set; }
	
	[Column("REDEMPTION_DATE")]
	public DateTime RedemptionDate { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	}

