// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.TicketingModule.Domain.Entities;
using QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.BookingItem;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Application.Services.BookingItem
{
    public partial class BookingItemService : IBookingItemService
    {
        private readonly ILogger<BookingItemService> _logger;
        private readonly IBookingItemRepository _repository;
        public BookingItemService(ILogger<BookingItemService> logger, IBookingItemRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<BookingItemDto>> InsertAsync(BookingItemDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(BookingItemDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, BookingItemDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<BookingItemDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<BookingItemDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByBookingResponseDto>>> GetByBookingAsync(int bookingItemBookingId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByBookingAsync(bookingItemBookingId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetBookingDetailsResponseDto>> GetBookingDetailsAsync(int bookingItemBookingId)
        {
            var returnValue = await _repository.GetBookingDetailsAsync(bookingItemBookingId);
            return returnValue.ToResponse();
        }
    }
}