// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.TicketingModule.Domain.Entities;
using QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.PaymentRecord;
using QuickCode.BirBilet.TicketingModule.Application.Mappings;
using QuickCode.BirBilet.TicketingModule.Persistence.Sql;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Persistence.Repositories
{
    public partial class PaymentRecordRepository : BaseRepository, IPaymentRecordRepository
    {
        public async Task<RepoResponse<List<GetByBookingResponseDto>>> GetByBookingAsync(int paymentRecordBookingId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(PaymentRecordCrudSqlBindings.OperationNames.GetByBooking, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByBookingResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.PaymentRecord.Query.GetByBooking);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PAYMENT_RECORD_BOOKING_ID = paymentRecordBookingId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByBookingResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in PaymentRecord");
                }
            });
        }

        public async Task<RepoResponse<List<GetByDateRangeResponseDto>>> GetByDateRangeAsync(DateTime paymentRecordPaymentDateFrom, DateTime paymentRecordPaymentDateTo, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(PaymentRecordCrudSqlBindings.OperationNames.GetByDateRange, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByDateRangeResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.PaymentRecord.Query.GetByDateRange);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PAYMENT_RECORD_PAYMENT_DATE_From = paymentRecordPaymentDateFrom,
                        PRM_PAYMENT_RECORD_PAYMENT_DATE_To = paymentRecordPaymentDateTo,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByDateRangeResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in PaymentRecord");
                }
            });
        }

        public async Task<RepoResponse<GetDailyPaymentsResponseDto>> GetDailyPaymentsAsync()
        {
            return await ExecuteWithExceptionHandling(PaymentRecordCrudSqlBindings.OperationNames.GetDailyPayments, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PaymentRecord.Query.GetDailyPayments);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetDailyPaymentsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in PaymentRecord");
            });
        }

        public async Task<RepoResponse<GetMonthlyPaymentsResponseDto>> GetMonthlyPaymentsAsync()
        {
            return await ExecuteWithExceptionHandling(PaymentRecordCrudSqlBindings.OperationNames.GetMonthlyPayments, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PaymentRecord.Query.GetMonthlyPayments);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetMonthlyPaymentsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in PaymentRecord");
            });
        }
    }
}