-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[BOOKINGS] (
    [BOOKING_NUMBER],
    [SCHEDULE_ID],
    [CUSTOMER_ID],
    [TOTAL_SEATS],
    [TOTAL_AMOUNT],
    [STATUS],
    [BOOKING_DATE],
    [EXPIRY_DATE],
    [CONFIRMATION_DATE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_BOOKING_BOOKING_NUMBER,
    @PRM_BOOKING_SCHEDULE_ID,
    @PRM_BOOKING_CUSTOMER_ID,
    @PRM_BOOKING_TOTAL_SEATS,
    @PRM_BOOKING_TOTAL_AMOUNT,
    @PRM_BOOKING_STATUS,
    @PRM_BOOKING_BOOKING_DATE,
    @PRM_BOOKING_EXPIRY_DATE,
    @PRM_BOOKING_CONFIRMATION_DATE,
    @PRM_BOOKING_CREATED_DATE
    );