// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.EventItem;

namespace QuickCode.BirBilet.EventManagementModule.Persistence.Repositories;
internal static class EventItemCrudSqlBindings
{
    public const string StoreTableName = "EVENT_ITEMS";
    public const string ParameterNamePrefix = "EVENT_ITEM";
    public const string IdParameterName = "PRM_EVENT_ITEM_ID";
    public static class OperationNames
    {
        public const string Cancel = "Cancel";
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByPk = "GetByPk";
        public const string GetByType = "GetByType";
        public const string GetPublished = "GetPublished";
        public const string GetRecent = "GetRecent";
        public const string GetTotalByType = "GetTotalByType";
        public const string GetUpcoming = "GetUpcoming";
        public const string Insert = "Insert";
        public const string MarkCompleted = "MarkCompleted";
        public const string Publish = "Publish";
        public const string SearchByName = "SearchByName";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("NAME", nameof(EventItemDto.Name)),
        ("DESCRIPTION", nameof(EventItemDto.Description)),
        ("EVENT_TYPE", nameof(EventItemDto.EventType)),
        ("STATUS", nameof(EventItemDto.Status)),
        ("DURATION_MINUTES", nameof(EventItemDto.DurationMinutes)),
        ("POSTER_URL", nameof(EventItemDto.PosterUrl)),
        ("IS_ACTIVE", nameof(EventItemDto.IsActive)),
        ("CREATED_DATE", nameof(EventItemDto.CreatedDate)),
        ("UPDATED_DATE", nameof(EventItemDto.UpdatedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("NAME", nameof(EventItemDto.Name)),
        ("DESCRIPTION", nameof(EventItemDto.Description)),
        ("EVENT_TYPE", nameof(EventItemDto.EventType)),
        ("STATUS", nameof(EventItemDto.Status)),
        ("DURATION_MINUTES", nameof(EventItemDto.DurationMinutes)),
        ("POSTER_URL", nameof(EventItemDto.PosterUrl)),
        ("IS_ACTIVE", nameof(EventItemDto.IsActive)),
        ("CREATED_DATE", nameof(EventItemDto.CreatedDate)),
        ("UPDATED_DATE", nameof(EventItemDto.UpdatedDate)),
        ("ID", nameof(EventItemDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(EventItemDto.Id))
    };
}