// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.EventManagementModule.Domain.Entities;
using QuickCode.BirBilet.EventManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.EventItem;
using QuickCode.BirBilet.EventManagementModule.Application.Mappings;
using QuickCode.BirBilet.EventManagementModule.Persistence.Sql;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Persistence.Repositories
{
    public partial class EventItemRepository : BaseRepository, IEventItemRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(EventItemCrudSqlBindings.OperationNames.GetActive, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.EventItem.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in EventItem");
                }
            });
        }

        public async Task<RepoResponse<List<GetByTypeResponseDto>>> GetByTypeAsync(EventKind eventItemEventType, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(EventItemCrudSqlBindings.OperationNames.GetByType, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByTypeResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.EventItem.Query.GetByType);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_EVENT_ITEM_EVENT_TYPE = eventItemEventType,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByTypeResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in EventItem");
                }
            });
        }

        public async Task<RepoResponse<List<GetPublishedResponseDto>>> GetPublishedAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(EventItemCrudSqlBindings.OperationNames.GetPublished, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetPublishedResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.EventItem.Query.GetPublished);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetPublishedResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in EventItem");
                }
            });
        }

        public async Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string eventItemName, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(EventItemCrudSqlBindings.OperationNames.SearchByName, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SearchByNameResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.EventItem.Query.SearchByName);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_EVENT_ITEM_NAME = eventItemName,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<SearchByNameResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in EventItem");
                }
            });
        }

        public async Task<RepoResponse<List<GetRecentResponseDto>>> GetRecentAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(EventItemCrudSqlBindings.OperationNames.GetRecent, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetRecentResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.EventItem.Query.GetRecent);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetRecentResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in EventItem");
                }
            });
        }

        public async Task<RepoResponse<List<GetUpcomingResponseDto>>> GetUpcomingAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(EventItemCrudSqlBindings.OperationNames.GetUpcoming, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetUpcomingResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.EventItem.Query.GetUpcoming);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetUpcomingResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in EventItem");
                }
            });
        }

        public async Task<RepoResponse<GetTotalByTypeResponseDto>> GetTotalByTypeAsync(EventKind eventItemEventType)
        {
            return await ExecuteWithExceptionHandling(EventItemCrudSqlBindings.OperationNames.GetTotalByType, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.EventItem.Query.GetTotalByType);
                var parameters = new
                {
                    PRM_EVENT_ITEM_EVENT_TYPE = eventItemEventType
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetTotalByTypeResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in EventItem");
            });
        }
    }
}