// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Hall
{
    public record GetUnderMaintenanceResponseDto
    {
        public int Id { get; init; }
        public int VenueId { get; init; }
        public string HallName { get; init; }
        public int Capacity { get; init; }
    }
}