-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT B.[ID], B.[BOOKING_NUMBER], B.[CUSTOMER_ID], B.[TOTAL_AMOUNT], B.[EXPIRY_DATE] 
FROM [BOOKINGS] B 
WHERE B.[IsDeleted] = 0 
	AND B.[STATUS] = 'PENDING' 
ORDER BY B.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 