-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 COUNT(*) AS TOTAL_BOOKINGS,
	SUM(B.[TOTAL_SEATS]) AS TOTAL_RESERVED_SEATS,
	SUM(B.[TOTAL_AMOUNT]) AS TOTAL_BOOKING_VALUE 
FROM [BOOKINGS] B 
WHERE B.[IsDeleted] = 0 
	AND B.[SCHEDULE_ID] = @PRM_BOOKING_SCHEDULE_ID 