-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT B.[ID], B.[BOOKING_NUMBER], B.[SCHEDULE_ID], B.[TOTAL_SEATS], B.[TOTAL_AMOUNT], B.[STATUS], B.[BOOKING_DATE] 
FROM [BOOKINGS] B 
WHERE B.[IsDeleted] = 0 
	AND B.[CUSTOMER_ID] = @PRM_BOOKING_CUSTOMER_ID 
ORDER BY B.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 