IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRICE_HISTORIES', N'U') AND name = N'IX_PRICE_HISTORIES_PRICING_ID')
BEGIN
    CREATE INDEX [IX_PRICE_HISTORIES_PRICING_ID] ON [dbo].[PRICE_HISTORIES] ([PRICING_ID]);
END