IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.BOOKING_ITEMS', N'U') AND name = N'IX_BOOKING_ITEMS_BOOKING_ID')
BEGIN
    CREATE INDEX [IX_BOOKING_ITEMS_BOOKING_ID] ON [dbo].[BOOKING_ITEMS] ([BOOKING_ID]);
END