IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRICE_HISTORIES_PRICINGS_PRICING_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRICE_HISTORIES'))
BEGIN
    ALTER TABLE [dbo].[PRICE_HISTORIES] ADD CONSTRAINT [FK_PRICE_HISTORIES_PRICINGS_PRICING_ID] FOREIGN KEY ([PRICING_ID]) REFERENCES [dbo].[PRICINGS] ([ID]);
END