IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PAYMENT_RECORDS', N'U') AND name = N'IX_PAYMENT_RECORDS_IsDeleted')
BEGIN
    CREATE INDEX [IX_PAYMENT_RECORDS_IsDeleted] ON [dbo].[PAYMENT_RECORDS] ([IsDeleted]);
END