IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TICKETS', N'U') AND name = N'IX_TICKETS_CUSTOMER_ID')
BEGIN
    CREATE INDEX [IX_TICKETS_CUSTOMER_ID] ON [dbo].[TICKETS] ([CUSTOMER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TICKETS', N'U') AND name = N'IX_TICKETS_SCHEDULE_ID_STATUS')
BEGIN
    CREATE INDEX [IX_TICKETS_SCHEDULE_ID_STATUS] ON [dbo].[TICKETS] ([SCHEDULE_ID], [STATUS]);
END