IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_BOOKING_ITEMS_BOOKINGS_BOOKING_ID' AND parent_object_id = OBJECT_ID(N'dbo.BOOKING_ITEMS'))
BEGIN
    ALTER TABLE [dbo].[BOOKING_ITEMS] ADD CONSTRAINT [FK_BOOKING_ITEMS_BOOKINGS_BOOKING_ID] FOREIGN KEY ([BOOKING_ID]) REFERENCES [dbo].[BOOKINGS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PAYMENT_RECORDS_BOOKINGS_BOOKING_ID' AND parent_object_id = OBJECT_ID(N'dbo.PAYMENT_RECORDS'))
BEGIN
    ALTER TABLE [dbo].[PAYMENT_RECORDS] ADD CONSTRAINT [FK_PAYMENT_RECORDS_BOOKINGS_BOOKING_ID] FOREIGN KEY ([BOOKING_ID]) REFERENCES [dbo].[BOOKINGS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRICE_HISTORIES_PRICINGS_PRICING_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRICE_HISTORIES'))
BEGIN
    ALTER TABLE [dbo].[PRICE_HISTORIES] ADD CONSTRAINT [FK_PRICE_HISTORIES_PRICINGS_PRICING_ID] FOREIGN KEY ([PRICING_ID]) REFERENCES [dbo].[PRICINGS] ([ID]);
END