IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PAYMENT_RECORDS', N'U') AND name = N'IX_PAYMENT_RECORDS_BOOKING_ID')
BEGIN
    CREATE INDEX [IX_PAYMENT_RECORDS_BOOKING_ID] ON [dbo].[PAYMENT_RECORDS] ([BOOKING_ID]);
END