IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRICE_HISTORIES', N'U') AND name = N'IX_PRICE_HISTORIES_IsDeleted')
BEGIN
    CREATE INDEX [IX_PRICE_HISTORIES_IsDeleted] ON [dbo].[PRICE_HISTORIES] ([IsDeleted]);
END