IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.BOOKINGS', N'U') AND name = N'IX_BOOKINGS_CUSTOMER_ID')
BEGIN
    CREATE INDEX [IX_BOOKINGS_CUSTOMER_ID] ON [dbo].[BOOKINGS] ([CUSTOMER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.BOOKINGS', N'U') AND name = N'IX_BOOKINGS_SCHEDULE_ID')
BEGIN
    CREATE INDEX [IX_BOOKINGS_SCHEDULE_ID] ON [dbo].[BOOKINGS] ([SCHEDULE_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.BOOKINGS', N'U') AND name = N'IX_BOOKINGS_STATUS_EXPIRY_DATE')
BEGIN
    CREATE INDEX [IX_BOOKINGS_STATUS_EXPIRY_DATE] ON [dbo].[BOOKINGS] ([STATUS], [EXPIRY_DATE]);
END