IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRICINGS', N'U') AND name = N'IX_PRICINGS_SCHEDULE_ID_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_PRICINGS_SCHEDULE_ID_IS_ACTIVE] ON [dbo].[PRICINGS] ([SCHEDULE_ID], [IS_ACTIVE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRICINGS', N'U') AND name = N'IX_PRICINGS_SCHEDULE_ID_PRICE_TYPE')
BEGIN
    CREATE INDEX [IX_PRICINGS_SCHEDULE_ID_PRICE_TYPE] ON [dbo].[PRICINGS] ([SCHEDULE_ID], [PRICE_TYPE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRICINGS', N'U') AND name = N'IX_PRICINGS_SCHEDULE_ID_SEAT_CATEGORY')
BEGIN
    CREATE INDEX [IX_PRICINGS_SCHEDULE_ID_SEAT_CATEGORY] ON [dbo].[PRICINGS] ([SCHEDULE_ID], [SEAT_CATEGORY]);
END