IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PAYMENT_RECORDS_BOOKINGS_BOOKING_ID' AND parent_object_id = OBJECT_ID(N'dbo.PAYMENT_RECORDS'))
BEGIN
    ALTER TABLE [dbo].[PAYMENT_RECORDS] ADD CONSTRAINT [FK_PAYMENT_RECORDS_BOOKINGS_BOOKING_ID] FOREIGN KEY ([BOOKING_ID]) REFERENCES [dbo].[BOOKINGS] ([ID]);
END