IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_BOOKING_ITEMS_BOOKINGS_BOOKING_ID' AND parent_object_id = OBJECT_ID(N'dbo.BOOKING_ITEMS'))
BEGIN
    ALTER TABLE [dbo].[BOOKING_ITEMS] ADD CONSTRAINT [FK_BOOKING_ITEMS_BOOKINGS_BOOKING_ID] FOREIGN KEY ([BOOKING_ID]) REFERENCES [dbo].[BOOKINGS] ([ID]);
END