// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirBilet.VenueManagementModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Seat
    {
        public static class Command
        {
            private const string _prefix = "VenueManagementModule.Seat.Command";
            private const string _sqlScriptStem = "Seat";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string MarkReserved => ResourceKey($"{_sqlScriptStem}.MarkReserved.g.sql");
            public static string MarkSold => ResourceKey($"{_sqlScriptStem}.MarkSold.g.sql");
            public static string MarkAvailable => ResourceKey($"{_sqlScriptStem}.MarkAvailable.g.sql");
            public static string BlockSeat => ResourceKey($"{_sqlScriptStem}.BlockSeat.g.sql");
        }
    }
}