-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[PRICINGS]
SET
    [SCHEDULE_ID] = @PRM_PRICING_SCHEDULE_ID,
    [SEAT_CATEGORY] = @PRM_PRICING_SEAT_CATEGORY,
    [PRICE_TYPE] = @PRM_PRICING_PRICE_TYPE,
    [BASE_PRICE] = @PRM_PRICING_BASE_PRICE,
    [DISCOUNT_PERCENTAGE] = @PRM_PRICING_DISCOUNT_PERCENTAGE,
    [FINAL_PRICE] = @PRM_PRICING_FINAL_PRICE,
    [VALID_FROM] = @PRM_PRICING_VALID_FROM,
    [VALID_TO] = @PRM_PRICING_VALID_TO,
    [IS_ACTIVE] = @PRM_PRICING_IS_ACTIVE,
    [CREATED_DATE] = @PRM_PRICING_CREATED_DATE
WHERE
    [ID] = @PRM_PRICING_ID
    AND [IsDeleted] = 0;