-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [SCHEDULE_ID],
    [SEAT_CATEGORY],
    [PRICE_TYPE],
    [BASE_PRICE],
    [DISCOUNT_PERCENTAGE],
    [FINAL_PRICE],
    [VALID_FROM],
    [VALID_TO],
    [IS_ACTIVE],
    [CREATED_DATE]
FROM [dbo].[PRICINGS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;