-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT SC.[ID], SC.[CATEGORY_NAME], SC.[DESCRIPTION] 
FROM [SEAT_CATEGORIES] SC 
WHERE SC.[IsDeleted] = 0 
	AND SC.[IS_ACTIVE] = 1 
ORDER BY SC.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 