-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[PAYMENT_RECORDS]
SET
    [BOOKING_ID] = @PRM_PAYMENT_RECORD_BOOKING_ID,
    [AMOUNT] = @PRM_PAYMENT_RECORD_AMOUNT,
    [PAYMENT_METHOD] = @PRM_PAYMENT_RECORD_PAYMENT_METHOD,
    [TRANSACTION_ID] = @PRM_PAYMENT_RECORD_TRANSACTION_ID,
    [PAYMENT_DATE] = @PRM_PAYMENT_RECORD_PAYMENT_DATE,
    [STATUS] = @PRM_PAYMENT_RECORD_STATUS,
    [CREATED_DATE] = @PRM_PAYMENT_RECORD_CREATED_DATE
WHERE
    [ID] = @PRM_PAYMENT_RECORD_ID
    AND [IsDeleted] = 0;