-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [BOOKING_ID],
    [AMOUNT],
    [PAYMENT_METHOD],
    [TRANSACTION_ID],
    [PAYMENT_DATE],
    [STATUS],
    [CREATED_DATE]
FROM [dbo].[PAYMENT_RECORDS]
WHERE
    [ID] = @PRM_PAYMENT_RECORD_ID
    AND [IsDeleted] = 0;