// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.TicketingModule.Domain.Entities;
using QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.Pricing;
using QuickCode.BirBilet.TicketingModule.Application.Mappings;
using QuickCode.BirBilet.TicketingModule.Persistence.Sql;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Persistence.Repositories
{
    public partial class PricingRepository : BaseRepository, IPricingRepository
    {
        public async Task<RepoResponse<List<GetByScheduleResponseDto>>> GetByScheduleAsync(int pricingScheduleId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(PricingCrudSqlBindings.OperationNames.GetBySchedule, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByScheduleResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Pricing.Query.GetBySchedule);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PRICING_SCHEDULE_ID = pricingScheduleId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByScheduleResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Pricing");
                }
            });
        }

        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int pricingScheduleId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(PricingCrudSqlBindings.OperationNames.GetActive, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Pricing.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PRICING_SCHEDULE_ID = pricingScheduleId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Pricing");
                }
            });
        }

        public async Task<RepoResponse<List<GetByCategoryResponseDto>>> GetByCategoryAsync(int pricingScheduleId, SeatCategory pricingSeatCategory, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(PricingCrudSqlBindings.OperationNames.GetByCategory, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCategoryResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Pricing.Query.GetByCategory);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PRICING_SCHEDULE_ID = pricingScheduleId,
                        PRM_PRICING_SEAT_CATEGORY = pricingSeatCategory,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByCategoryResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Pricing");
                }
            });
        }

        public async Task<RepoResponse<List<GetEarlyBirdResponseDto>>> GetEarlyBirdAsync(int pricingScheduleId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(PricingCrudSqlBindings.OperationNames.GetEarlyBird, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetEarlyBirdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Pricing.Query.GetEarlyBird);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PRICING_SCHEDULE_ID = pricingScheduleId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetEarlyBirdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Pricing");
                }
            });
        }

        public async Task<RepoResponse<List<GetPremiumPricingResponseDto>>> GetPremiumPricingAsync(int pricingScheduleId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(PricingCrudSqlBindings.OperationNames.GetPremiumPricing, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetPremiumPricingResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Pricing.Query.GetPremiumPricing);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PRICING_SCHEDULE_ID = pricingScheduleId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetPremiumPricingResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Pricing");
                }
            });
        }

        public async Task<RepoResponse<GetPricingSummaryResponseDto>> GetPricingSummaryAsync(int pricingScheduleId)
        {
            return await ExecuteWithExceptionHandling(PricingCrudSqlBindings.OperationNames.GetPricingSummary, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Pricing.Query.GetPricingSummary);
                var parameters = new
                {
                    PRM_PRICING_SCHEDULE_ID = pricingScheduleId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetPricingSummaryResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Pricing");
            });
        }
    }
}