// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirBilet.TicketingModule.Application.Dtos.Pricing;

namespace QuickCode.BirBilet.TicketingModule.Persistence.Repositories;
internal static class PricingCrudSqlBindings
{
    public const string StoreTableName = "PRICINGS";
    public const string ParameterNamePrefix = "PRICING";
    public const string IdParameterName = "PRM_PRICING_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByCategory = "GetByCategory";
        public const string GetByPk = "GetByPk";
        public const string GetBySchedule = "GetBySchedule";
        public const string GetEarlyBird = "GetEarlyBird";
        public const string GetPremiumPricing = "GetPremiumPricing";
        public const string GetPricingSummary = "GetPricingSummary";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
        public const string UpdatePrice = "UpdatePrice";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("SCHEDULE_ID", nameof(PricingDto.ScheduleId)),
        ("SEAT_CATEGORY", nameof(PricingDto.SeatCategory)),
        ("PRICE_TYPE", nameof(PricingDto.PriceType)),
        ("BASE_PRICE", nameof(PricingDto.BasePrice)),
        ("DISCOUNT_PERCENTAGE", nameof(PricingDto.DiscountPercentage)),
        ("FINAL_PRICE", nameof(PricingDto.FinalPrice)),
        ("VALID_FROM", nameof(PricingDto.ValidFrom)),
        ("VALID_TO", nameof(PricingDto.ValidTo)),
        ("IS_ACTIVE", nameof(PricingDto.IsActive)),
        ("CREATED_DATE", nameof(PricingDto.CreatedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("SCHEDULE_ID", nameof(PricingDto.ScheduleId)),
        ("SEAT_CATEGORY", nameof(PricingDto.SeatCategory)),
        ("PRICE_TYPE", nameof(PricingDto.PriceType)),
        ("BASE_PRICE", nameof(PricingDto.BasePrice)),
        ("DISCOUNT_PERCENTAGE", nameof(PricingDto.DiscountPercentage)),
        ("FINAL_PRICE", nameof(PricingDto.FinalPrice)),
        ("VALID_FROM", nameof(PricingDto.ValidFrom)),
        ("VALID_TO", nameof(PricingDto.ValidTo)),
        ("IS_ACTIVE", nameof(PricingDto.IsActive)),
        ("CREATED_DATE", nameof(PricingDto.CreatedDate)),
        ("ID", nameof(PricingDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(PricingDto.Id))
    };
}