// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.VenueManagementModule.Domain.Entities;
using QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Hall;
using QuickCode.BirBilet.VenueManagementModule.Application.Mappings;
using QuickCode.BirBilet.VenueManagementModule.Persistence.Sql;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Persistence.Repositories
{
    public partial class HallRepository : BaseRepository, IHallRepository
    {
        public async Task<RepoResponse<int>> SetMaintenanceAsync(int hallId, SetMaintenanceRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(HallCrudSqlBindings.OperationNames.SetMaintenance, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Hall.Command.SetMaintenance);
                var parameters = new
                {
                    PRM_HALL_ID = hallId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> ReopenAsync(int hallId, ReopenRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(HallCrudSqlBindings.OperationNames.Reopen, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Hall.Command.Reopen);
                var parameters = new
                {
                    PRM_HALL_ID = hallId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> DeactivateAsync(int hallId, DeactivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(HallCrudSqlBindings.OperationNames.Deactivate, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Hall.Command.Deactivate);
                var parameters = new
                {
                    PRM_HALL_ID = hallId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}