// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.VenueManagementModule.Domain.Entities;
using QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Venue;
using QuickCode.BirBilet.VenueManagementModule.Application.Mappings;
using QuickCode.BirBilet.VenueManagementModule.Persistence.Sql;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Persistence.Repositories
{
    public partial class VenueRepository : BaseRepository, IVenueRepository
    {
        public async Task<RepoResponse<int>> DeactivateAsync(int venueId, DeactivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(VenueCrudSqlBindings.OperationNames.Deactivate, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Venue.Command.Deactivate);
                var parameters = new
                {
                    PRM_VENUE_ID = venueId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> UpdateContactAsync(int venueId, UpdateContactRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(VenueCrudSqlBindings.OperationNames.UpdateContact, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Venue.Command.UpdateContact);
                var parameters = new
                {
                    VENUE_PHONE = updateRequest.VenuePhone,
                    VENUE_EMAIL = updateRequest.VenueEmail,
                    VENUE_WEBSITE_URL = updateRequest.VenueWebsiteUrl,
                    PRM_VENUE_ID = venueId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}