// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Venue;

namespace QuickCode.BirBilet.VenueManagementModule.Persistence.Repositories;
internal static class VenueCrudSqlBindings
{
    public const string StoreTableName = "VENUES";
    public const string ParameterNamePrefix = "VENUE";
    public const string IdParameterName = "PRM_VENUE_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByCity = "GetByCity";
        public const string GetByPk = "GetByPk";
        public const string GetByType = "GetByType";
        public const string GetWithContact = "GetWithContact";
        public const string Insert = "Insert";
        public const string SearchByName = "SearchByName";
        public const string Select = "Select";
        public const string Update = "Update";
        public const string UpdateContact = "UpdateContact";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("NAME", nameof(VenueDto.Name)),
        ("ADDRESS", nameof(VenueDto.Address)),
        ("CITY", nameof(VenueDto.City)),
        ("COUNTRY", nameof(VenueDto.Country)),
        ("VENUE_TYPE", nameof(VenueDto.VenueType)),
        ("PHONE", nameof(VenueDto.Phone)),
        ("EMAIL", nameof(VenueDto.Email)),
        ("WEBSITE_URL", nameof(VenueDto.WebsiteUrl)),
        ("TOTAL_HALLS", nameof(VenueDto.TotalHalls)),
        ("IS_ACTIVE", nameof(VenueDto.IsActive)),
        ("CREATED_DATE", nameof(VenueDto.CreatedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("NAME", nameof(VenueDto.Name)),
        ("ADDRESS", nameof(VenueDto.Address)),
        ("CITY", nameof(VenueDto.City)),
        ("COUNTRY", nameof(VenueDto.Country)),
        ("VENUE_TYPE", nameof(VenueDto.VenueType)),
        ("PHONE", nameof(VenueDto.Phone)),
        ("EMAIL", nameof(VenueDto.Email)),
        ("WEBSITE_URL", nameof(VenueDto.WebsiteUrl)),
        ("TOTAL_HALLS", nameof(VenueDto.TotalHalls)),
        ("IS_ACTIVE", nameof(VenueDto.IsActive)),
        ("CREATED_DATE", nameof(VenueDto.CreatedDate)),
        ("ID", nameof(VenueDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(VenueDto.Id))
    };
}