-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [SCHEDULES] 
	SET [AVAILABLE_SEATS] = @SCHEDULE_AVAILABLE_SEATS 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_SCHEDULE_ID