-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[BOOKING_ITEMS] (
    [BOOKING_ID],
    [SEAT_ID],
    [PRICE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_BOOKING_ITEM_BOOKING_ID,
    @PRM_BOOKING_ITEM_SEAT_ID,
    @PRM_BOOKING_ITEM_PRICE,
    @PRM_BOOKING_ITEM_CREATED_DATE
    );