// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.EventManagementModule.Domain.Entities;
using QuickCode.BirBilet.EventManagementModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.ScheduleHistory;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Application.Services.ScheduleHistory
{
    public partial class ScheduleHistoryService : IScheduleHistoryService
    {
        private readonly ILogger<ScheduleHistoryService> _logger;
        private readonly IScheduleHistoryRepository _repository;
        public ScheduleHistoryService(ILogger<ScheduleHistoryService> logger, IScheduleHistoryRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<ScheduleHistoryDto>> InsertAsync(ScheduleHistoryDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(ScheduleHistoryDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, ScheduleHistoryDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<ScheduleHistoryDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<ScheduleHistoryDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByScheduleResponseDto>>> GetByScheduleAsync(int scheduleHistoryScheduleId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByScheduleAsync(scheduleHistoryScheduleId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetRecentChangesResponseDto>>> GetRecentChangesAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetRecentChangesAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }
    }
}