// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.VenueManagementModule.Domain.Entities;
using QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Hall;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Application.Services.Hall
{
    public partial class HallService : IHallService
    {
        private readonly ILogger<HallService> _logger;
        private readonly IHallRepository _repository;
        public HallService(ILogger<HallService> logger, IHallRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<HallDto>> InsertAsync(HallDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(HallDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, HallDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<HallDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<HallDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByVenueResponseDto>>> GetByVenueAsync(int hallVenueId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByVenueAsync(hallVenueId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetActiveAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetActiveByVenueResponseDto>>> GetActiveByVenueAsync(int hallVenueId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetActiveByVenueAsync(hallVenueId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetUnderMaintenanceResponseDto>>> GetUnderMaintenanceAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetUnderMaintenanceAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetHallSummaryResponseDto>> GetHallSummaryAsync(int hallVenueId)
        {
            var returnValue = await _repository.GetHallSummaryAsync(hallVenueId);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> SetMaintenanceAsync(int hallId, SetMaintenanceRequestDto updateRequest)
        {
            var returnValue = await _repository.SetMaintenanceAsync(hallId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> ReopenAsync(int hallId, ReopenRequestDto updateRequest)
        {
            var returnValue = await _repository.ReopenAsync(hallId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> DeactivateAsync(int hallId, DeactivateRequestDto updateRequest)
        {
            var returnValue = await _repository.DeactivateAsync(hallId, updateRequest);
            return returnValue.ToResponse();
        }
    }
}