// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Web.Controllers;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.Booking;
using QuickCode.BirBilet.TicketingModule.Application.Services.Booking;
using QuickCode.BirBilet.TicketingModule.Domain.Enums;

namespace QuickCode.BirBilet.TicketingModule.Api.Controllers
{
    public partial class BookingsController : QuickCodeBaseApiController
    {
        private readonly IBookingService service;
        private readonly ILogger<BookingsController> logger;
        private readonly IServiceProvider serviceProvider;
        public BookingsController(IBookingService service, IServiceProvider serviceProvider, ILogger<BookingsController> logger)
        {
            this.service = service;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<BookingDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await service.ListAsync(page, size);
            if (HandleResponseError(response, logger, "Booking", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await service.TotalItemCountAsync();
            if (HandleResponseError(response, logger, "Booking") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(BookingDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await service.GetItemAsync(id);
            if (HandleResponseError(response, logger, "Booking", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(BookingDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(BookingDto model)
        {
            var response = await service.InsertAsync(model);
            if (HandleResponseError(response, logger, "Booking") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, BookingDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await service.UpdateAsync(id, model);
            if (HandleResponseError(response, logger, "Booking", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await service.DeleteItemAsync(id);
            if (HandleResponseError(response, logger, "Booking", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-customer/{bookingCustomerId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByCustomerResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByCustomerAsync(int bookingCustomerId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetByCustomerAsync(bookingCustomerId, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Booking", $"BookingCustomerId: '{bookingCustomerId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-schedule/{bookingScheduleId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByScheduleResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByScheduleAsync(int bookingScheduleId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetByScheduleAsync(bookingScheduleId, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Booking", $"BookingScheduleId: '{bookingScheduleId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-pending")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetPendingResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetPendingAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetPendingAsync(pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Booking", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-confirmed")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetConfirmedResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetConfirmedAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetConfirmedAsync(pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Booking", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-expired")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetExpiredResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetExpiredAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetExpiredAsync(pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Booking", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-pending-expiring")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetPendingExpiringResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetPendingExpiringAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetPendingExpiringAsync(pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Booking", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-today-bookings")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetTodayBookingsResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetTodayBookingsAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetTodayBookingsAsync(pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Booking", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-booking-summary/{bookingScheduleId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetBookingSummaryResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetBookingSummaryAsync(int bookingScheduleId)
        {
            var response = await service.GetBookingSummaryAsync(bookingScheduleId);
            if (HandleResponseError(response, logger, "Booking", $"BookingScheduleId: '{bookingScheduleId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-monthly-booking-stats")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetMonthlyBookingStatsResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetMonthlyBookingStatsAsync()
        {
            var response = await service.GetMonthlyBookingStatsAsync();
            if (HandleResponseError(response, logger, "Booking", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("confirm/{bookingId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ConfirmAsync(int bookingId, [FromBody] ConfirmRequestDto updateRequest)
        {
            var response = await service.ConfirmAsync(bookingId, updateRequest);
            if (HandleResponseError(response, logger, "Booking", $"BookingId: '{bookingId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("mark-expired/{bookingId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> MarkExpiredAsync(int bookingId, [FromBody] MarkExpiredRequestDto updateRequest)
        {
            var response = await service.MarkExpiredAsync(bookingId, updateRequest);
            if (HandleResponseError(response, logger, "Booking", $"BookingId: '{bookingId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("cancel/{bookingId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CancelAsync(int bookingId, [FromBody] CancelRequestDto updateRequest)
        {
            var response = await service.CancelAsync(bookingId, updateRequest);
            if (HandleResponseError(response, logger, "Booking", $"BookingId: '{bookingId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("complete/{bookingId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CompleteAsync(int bookingId, [FromBody] CompleteRequestDto updateRequest)
        {
            var response = await service.CompleteAsync(bookingId, updateRequest);
            if (HandleResponseError(response, logger, "Booking", $"BookingId: '{bookingId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}