// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirBilet.VenueManagementModule.Domain;
using QuickCode.BirBilet.Domain.Shared.Abstractions;
using QuickCode.BirBilet.Domain.Shared.Entities;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Domain.Entities;

[Table("HALLS")]
public partial class Hall : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("VENUE_ID")]
	public int VenueId { get; set; }
	
	[Column("HALL_NAME")]
	[StringLength(50)]
	public string HallName { get; set; }
	
	[Column("HALL_NUMBER")]
	[StringLength(50)]
	public string HallNumber { get; set; }
	
	[Column("CAPACITY")]
	public int Capacity { get; set; }
	
	[Column("TOTAL_ROWS")]
	public int TotalRows { get; set; }
	
	[Column("TOTAL_COLUMNS")]
	public int TotalColumns { get; set; }
	
	[Column("STATUS", TypeName = "nvarchar(50)")]
	public HallStatus Status { get; set; }
	
	[Column("IS_ACTIVE")]
	public bool IsActive { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	
	[InverseProperty(nameof(Seat.Hall))]
	public virtual ICollection<Seat> Seats { get; } = new List<Seat>();

	[ForeignKey("VenueId")]
	[InverseProperty(nameof(Venue.Halls))]
	public virtual Venue Venue { get; set; } = null!;
}

