// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using Xunit;
using Microsoft.Extensions.Logging;
using Moq;
using QuickCode.BirBilet.EventManagementModule.Persistence.Repositories;
using QuickCode.BirBilet.Infrastructure.Data;
using Xunit.Abstractions;

namespace QuickCode.BirBilet.EventManagementModule.Persistence.Tests.Repositories
{
    public class ScheduleRepositoryTests : IDisposable
    {
        private readonly Mock<IDbConnectionFactory> connectionFactoryMock;
        private readonly Mock<ILogger<ScheduleRepository>> loggerMock;
        private readonly ITestOutputHelper _output;
        public ScheduleRepositoryTests(ITestOutputHelper output)
        {
            _output = output;
            connectionFactoryMock = new Mock<IDbConnectionFactory>();
            loggerMock = new Mock<ILogger<ScheduleRepository>>();
        }

        private ScheduleRepository CreateRepository()
        {
            return new ScheduleRepository(loggerMock.Object, connectionFactoryMock.Object);
        }

        [Fact]
        public void Constructor_Should_Create_Repository_With_Connection_Factory()
        {
            var repository = CreateRepository();
            Assert.NotNull(repository);
        }

        public void Dispose()
        {
            _output.WriteLine("Repository tests use IDbConnectionFactory. Provider-specific integration coverage belongs in relational DB test fixtures.");
        }
    }
}