// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.Schedule;

namespace QuickCode.BirBilet.EventManagementModule.Persistence.Repositories;
internal static class ScheduleCrudSqlBindings
{
    public const string StoreTableName = "SCHEDULES";
    public const string ParameterNamePrefix = "SCHEDULE";
    public const string IdParameterName = "PRM_SCHEDULE_ID";
    public static class OperationNames
    {
        public const string CancelSchedule = "CancelSchedule";
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetAvailable = "GetAvailable";
        public const string GetByDateRange = "GetByDateRange";
        public const string GetByEvent = "GetByEvent";
        public const string GetByPk = "GetByPk";
        public const string GetByVenue = "GetByVenue";
        public const string GetScheduleSummary = "GetScheduleSummary";
        public const string GetSoldOut = "GetSoldOut";
        public const string GetTodaySchedules = "GetTodaySchedules";
        public const string GetUpcomingSchedules = "GetUpcomingSchedules";
        public const string Insert = "Insert";
        public const string MarkSoldOut = "MarkSoldOut";
        public const string Select = "Select";
        public const string Update = "Update";
        public const string UpdateAvailableSeats = "UpdateAvailableSeats";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("EVENT_ID", nameof(ScheduleDto.EventId)),
        ("VENUE_ID", nameof(ScheduleDto.VenueId)),
        ("HALL_ID", nameof(ScheduleDto.HallId)),
        ("SCHEDULE_DATE", nameof(ScheduleDto.ScheduleDate)),
        ("START_TIME", nameof(ScheduleDto.StartTime)),
        ("END_TIME", nameof(ScheduleDto.EndTime)),
        ("STATUS", nameof(ScheduleDto.Status)),
        ("TOTAL_SEATS", nameof(ScheduleDto.TotalSeats)),
        ("AVAILABLE_SEATS", nameof(ScheduleDto.AvailableSeats)),
        ("CREATED_DATE", nameof(ScheduleDto.CreatedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("EVENT_ID", nameof(ScheduleDto.EventId)),
        ("VENUE_ID", nameof(ScheduleDto.VenueId)),
        ("HALL_ID", nameof(ScheduleDto.HallId)),
        ("SCHEDULE_DATE", nameof(ScheduleDto.ScheduleDate)),
        ("START_TIME", nameof(ScheduleDto.StartTime)),
        ("END_TIME", nameof(ScheduleDto.EndTime)),
        ("STATUS", nameof(ScheduleDto.Status)),
        ("TOTAL_SEATS", nameof(ScheduleDto.TotalSeats)),
        ("AVAILABLE_SEATS", nameof(ScheduleDto.AvailableSeats)),
        ("CREATED_DATE", nameof(ScheduleDto.CreatedDate)),
        ("ID", nameof(ScheduleDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(ScheduleDto.Id))
    };
}