// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QcEntity = global::QuickCode.BirBilet.EventManagementModule.Domain.Entities;
using QuickCode.BirBilet.EventManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.Schedule;
using QuickCode.BirBilet.EventManagementModule.Application.Mappings;
using QuickCode.BirBilet.EventManagementModule.Persistence.Sql;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Persistence.Repositories
{
    public partial class ScheduleRepository : BaseRepository, IScheduleRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public ScheduleRepository(ILogger<ScheduleRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "Schedule")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<ScheduleDto>> InsertAsync(ScheduleDto value)
        {
            return await ExecuteWithExceptionHandling(ScheduleCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Schedule.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(ScheduleCrudSqlBindings.ParameterNamePrefix, value, ScheduleCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.Schedule>(sql, p);
                return new RepoResponse<ScheduleDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(ScheduleDto value)
        {
            return await ExecuteWithExceptionHandling(ScheduleCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Schedule.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(ScheduleCrudSqlBindings.ParameterNamePrefix, value, ScheduleCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(ScheduleDto value)
        {
            return await ExecuteWithExceptionHandling(ScheduleCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Schedule.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(ScheduleCrudSqlBindings.ParameterNamePrefix, value, ScheduleCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<ScheduleDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(ScheduleCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Schedule.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(ScheduleCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.Schedule>(sql, p);
                return row == null ? CreateNotFoundResponse<ScheduleDto>("Not found in Schedule") : new RepoResponse<ScheduleDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<ScheduleDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(ScheduleCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<ScheduleDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.Schedule.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.Schedule>(sql, p);
                return new RepoResponse<List<ScheduleDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(ScheduleCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Schedule.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}