// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.EventManagementModule.Domain.Entities;
using QuickCode.BirBilet.EventManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Data;
using QuickCode.BirBilet.Infrastructure.Data.Extensions;
using QuickCode.BirBilet.Infrastructure.Data.Helpers;
using QuickCode.BirBilet.EventManagementModule.Application.Dtos.Schedule;
using QuickCode.BirBilet.EventManagementModule.Application.Mappings;
using QuickCode.BirBilet.EventManagementModule.Persistence.Sql;
using QuickCode.BirBilet.EventManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.EventManagementModule.Persistence.Repositories
{
    public partial class ScheduleRepository : BaseRepository, IScheduleRepository
    {
        public async Task<RepoResponse<int>> UpdateAvailableSeatsAsync(int scheduleId, UpdateAvailableSeatsRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ScheduleCrudSqlBindings.OperationNames.UpdateAvailableSeats, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Schedule.Command.UpdateAvailableSeats);
                var parameters = new
                {
                    SCHEDULE_AVAILABLE_SEATS = updateRequest.ScheduleAvailableSeats,
                    PRM_SCHEDULE_ID = scheduleId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> MarkSoldOutAsync(int scheduleId, MarkSoldOutRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ScheduleCrudSqlBindings.OperationNames.MarkSoldOut, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Schedule.Command.MarkSoldOut);
                var parameters = new
                {
                    PRM_SCHEDULE_ID = scheduleId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> CancelScheduleAsync(int scheduleId, CancelScheduleRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ScheduleCrudSqlBindings.OperationNames.CancelSchedule, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Schedule.Command.CancelSchedule);
                var parameters = new
                {
                    PRM_SCHEDULE_ID = scheduleId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}