-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT SH.[SCHEDULE_ID], SH.[NEW_STATUS], SH.[CHANGED_DATE] 
FROM [SCHEDULE_HISTORIES] SH 
WHERE SH.[IsDeleted] = 0 
	AND SH.[CHANGED_DATE] > DATEADD(DAY, -7,
	GETDATE()) 
ORDER BY 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 