// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.VenueManagementModule.Application.Services.Hall;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Hall;
using QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.Infrastructure.Web.Helpers;
using QuickCode.BirBilet.Application.Contracts;

namespace QuickCode.BirBilet.VenueManagementModule.Application.Tests.Services.Hall
{
    public class InsertHallCommandTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<IHallRepository> _repositoryMock;
        private readonly Mock<ILogger<HallService>> _loggerMock;
        private readonly HallService _service;
        public InsertHallCommandTests()
        {
            _repositoryMock = new Mock<IHallRepository>();
            _loggerMock = new Mock<ILogger<HallService>>();
            _service = new HallService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_Success_When_Valid_Request()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<HallDto>("tr");
            var fakeResponse = new RepoResponse<HallDto>(fakeDto, "Success");
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<HallDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeDto, result.Value);
            _repositoryMock.Verify(r => r.InsertAsync(It.IsAny<HallDto>()), Times.Once);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_NotFound_When_Repository_Returns_404()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<HallDto>("tr");
            var fakeResponse = new RepoResponse<HallDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<HallDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.Null(result.Value);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}