// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.TicketingModule.Application.Services.PaymentRecord;
using QuickCode.BirBilet.TicketingModule.Application.Dtos.PaymentRecord;
using QuickCode.BirBilet.TicketingModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.Infrastructure.Web.Helpers;
using QuickCode.BirBilet.Application.Contracts;

namespace QuickCode.BirBilet.TicketingModule.Application.Tests.Services.PaymentRecord
{
    public class InsertPaymentRecordCommandTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<IPaymentRecordRepository> _repositoryMock;
        private readonly Mock<ILogger<PaymentRecordService>> _loggerMock;
        private readonly PaymentRecordService _service;
        public InsertPaymentRecordCommandTests()
        {
            _repositoryMock = new Mock<IPaymentRecordRepository>();
            _loggerMock = new Mock<ILogger<PaymentRecordService>>();
            _service = new PaymentRecordService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_Success_When_Valid_Request()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<PaymentRecordDto>("tr");
            var fakeResponse = new RepoResponse<PaymentRecordDto>(fakeDto, "Success");
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<PaymentRecordDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeDto, result.Value);
            _repositoryMock.Verify(r => r.InsertAsync(It.IsAny<PaymentRecordDto>()), Times.Once);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_NotFound_When_Repository_Returns_404()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<PaymentRecordDto>("tr");
            var fakeResponse = new RepoResponse<PaymentRecordDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<PaymentRecordDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.Null(result.Value);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}