-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT S.[ID], S.[SEAT_NUMBER], S.[ROW_NUMBER], S.[COLUMN_NUMBER], S.[CATEGORY], S.[STATUS] 
FROM [SEATS] S 
WHERE S.[IsDeleted] = 0 
	AND S.[HALL_ID] = @PRM_SEAT_HALL_ID 
ORDER BY S.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 