-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 [CATEGORY], COUNT(*) AS SEAT_COUNT 
FROM [SEATS] S 
WHERE S.[IsDeleted] = 0 
	AND S.[HALL_ID] = @PRM_SEAT_HALL_ID 
GROUP BY S.[CATEGORY] 
ORDER BY S.[CATEGORY] 