// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirBilet.VenueManagementModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Seat
    {
        public static class Query
        {
            private const string _prefix = "VenueManagementModule.Seat.Query";
            private const string _sqlScriptStem = "Seat";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetByHall => ResourceKey($"{_sqlScriptStem}.GetByHall.g.sql");
            public static string GetAvailable => ResourceKey($"{_sqlScriptStem}.GetAvailable.g.sql");
            public static string GetByCategory => ResourceKey($"{_sqlScriptStem}.GetByCategory.g.sql");
            public static string GetPremiumSeats => ResourceKey($"{_sqlScriptStem}.GetPremiumSeats.g.sql");
            public static string GetDisabledAccess => ResourceKey($"{_sqlScriptStem}.GetDisabledAccess.g.sql");
            public static string GetAvailableByRow => ResourceKey($"{_sqlScriptStem}.GetAvailableByRow.g.sql");
            public static string GetCategoryBreakdown => ResourceKey($"{_sqlScriptStem}.GetCategoryBreakdown.g.sql");
        }
    }
}