// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuickCode.BirBilet.TicketingModule.Domain.Enums;

public enum TicketStatus{
	[Description("Ticket available for purchase")]
	Available,
	[Description("Ticket sold")]
	Sold,
	[Description("Ticket reserved")]
	Reserved,
	[Description("Ticket cancelled")]
	Cancelled,
	[Description("Ticket redeemed/used")]
	Redeemed
}
