-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT PR.[ID], PR.[BOOKING_ID], PR.[AMOUNT], PR.[PAYMENT_METHOD], PR.[PAYMENT_DATE] 
FROM [PAYMENT_RECORDS] PR 
WHERE PR.[IsDeleted] = 0 
	AND PR.[PAYMENT_DATE] BETWEEN @PRM_PAYMENT_RECORD_PAYMENT_DATE_From 
	AND @PRM_PAYMENT_RECORD_PAYMENT_DATE_To 
ORDER BY PR.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 