-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[SEAT_CATEGORIES] (
    [CATEGORY_NAME],
    [DESCRIPTION],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_SEAT_CATEGORY_CATEGORY_NAME,
    @PRM_SEAT_CATEGORY_DESCRIPTION,
    @PRM_SEAT_CATEGORY_IS_ACTIVE
    );