-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[SEAT_CATEGORIES]
SET
    [CATEGORY_NAME] = @PRM_SEAT_CATEGORY_CATEGORY_NAME,
    [DESCRIPTION] = @PRM_SEAT_CATEGORY_DESCRIPTION,
    [IS_ACTIVE] = @PRM_SEAT_CATEGORY_IS_ACTIVE
WHERE
    [ID] = @PRM_SEAT_CATEGORY_ID
    AND [IsDeleted] = 0;