-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [CATEGORY_NAME],
    [DESCRIPTION],
    [IS_ACTIVE]
FROM [dbo].[SEAT_CATEGORIES]
WHERE
    [ID] = @PRM_SEAT_CATEGORY_ID
    AND [IsDeleted] = 0;