IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SCHEDULE_HISTORIES', N'U') AND name = N'IX_SCHEDULE_HISTORIES_SCHEDULE_ID')
BEGIN
    CREATE INDEX [IX_SCHEDULE_HISTORIES_SCHEDULE_ID] ON [dbo].[SCHEDULE_HISTORIES] ([SCHEDULE_ID]);
END