IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SCHEDULES', N'U') AND name = N'IX_SCHEDULES_EVENT_ID')
BEGIN
    CREATE INDEX [IX_SCHEDULES_EVENT_ID] ON [dbo].[SCHEDULES] ([EVENT_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SCHEDULES', N'U') AND name = N'IX_SCHEDULES_VENUE_ID')
BEGIN
    CREATE INDEX [IX_SCHEDULES_VENUE_ID] ON [dbo].[SCHEDULES] ([VENUE_ID]);
END