IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SCHEDULE_HISTORIES_SCHEDULES_SCHEDULE_ID' AND parent_object_id = OBJECT_ID(N'dbo.SCHEDULE_HISTORIES'))
BEGIN
    ALTER TABLE [dbo].[SCHEDULE_HISTORIES] ADD CONSTRAINT [FK_SCHEDULE_HISTORIES_SCHEDULES_SCHEDULE_ID] FOREIGN KEY ([SCHEDULE_ID]) REFERENCES [dbo].[SCHEDULES] ([ID]);
END