IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SCHEDULE_HISTORIES', N'U') AND name = N'IX_SCHEDULE_HISTORIES_IsDeleted')
BEGIN
    CREATE INDEX [IX_SCHEDULE_HISTORIES_IsDeleted] ON [dbo].[SCHEDULE_HISTORIES] ([IsDeleted]);
END