IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.EVENT_ITEMS', N'U') AND name = N'IX_EVENT_ITEMS_EVENT_TYPE')
BEGIN
    CREATE INDEX [IX_EVENT_ITEMS_EVENT_TYPE] ON [dbo].[EVENT_ITEMS] ([EVENT_TYPE]);
END