IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SCHEDULES_EVENT_ITEMS_EVENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.SCHEDULES'))
BEGIN
    ALTER TABLE [dbo].[SCHEDULES] ADD CONSTRAINT [FK_SCHEDULES_EVENT_ITEMS_EVENT_ID] FOREIGN KEY ([EVENT_ID]) REFERENCES [dbo].[EVENT_ITEMS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SCHEDULE_HISTORIES_SCHEDULES_SCHEDULE_ID' AND parent_object_id = OBJECT_ID(N'dbo.SCHEDULE_HISTORIES'))
BEGIN
    ALTER TABLE [dbo].[SCHEDULE_HISTORIES] ADD CONSTRAINT [FK_SCHEDULE_HISTORIES_SCHEDULES_SCHEDULE_ID] FOREIGN KEY ([SCHEDULE_ID]) REFERENCES [dbo].[SCHEDULES] ([ID]);
END