IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SCHEDULES_EVENT_ITEMS_EVENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.SCHEDULES'))
BEGIN
    ALTER TABLE [dbo].[SCHEDULES] ADD CONSTRAINT [FK_SCHEDULES_EVENT_ITEMS_EVENT_ID] FOREIGN KEY ([EVENT_ID]) REFERENCES [dbo].[EVENT_ITEMS] ([ID]);
END