// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.BirBilet.Infrastructure.Web.Controllers;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Seat;
using QuickCode.BirBilet.VenueManagementModule.Application.Services.Seat;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Api.Controllers
{
    public partial class SeatsController : QuickCodeBaseApiController
    {
        private readonly ISeatService service;
        private readonly ILogger<SeatsController> logger;
        private readonly IServiceProvider serviceProvider;
        public SeatsController(ISeatService service, IServiceProvider serviceProvider, ILogger<SeatsController> logger)
        {
            this.service = service;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<SeatDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await service.ListAsync(page, size);
            if (HandleResponseError(response, logger, "Seat", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await service.TotalItemCountAsync();
            if (HandleResponseError(response, logger, "Seat") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(SeatDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await service.GetItemAsync(id);
            if (HandleResponseError(response, logger, "Seat", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(SeatDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(SeatDto model)
        {
            var response = await service.InsertAsync(model);
            if (HandleResponseError(response, logger, "Seat") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, SeatDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await service.UpdateAsync(id, model);
            if (HandleResponseError(response, logger, "Seat", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await service.DeleteItemAsync(id);
            if (HandleResponseError(response, logger, "Seat", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-hall/{seatHallId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByHallResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByHallAsync(int seatHallId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetByHallAsync(seatHallId, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Seat", $"SeatHallId: '{seatHallId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-available/{seatHallId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetAvailableResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetAvailableAsync(int seatHallId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetAvailableAsync(seatHallId, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Seat", $"SeatHallId: '{seatHallId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-category/{seatHallId:int}/{seatCategory}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByCategoryResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByCategoryAsync(int seatHallId, SeatCategoryKind seatCategory, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetByCategoryAsync(seatHallId, seatCategory, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Seat", $"SeatHallId: '{seatHallId}', SeatCategory: '{seatCategory}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-premium-seats/{seatHallId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetPremiumSeatsResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetPremiumSeatsAsync(int seatHallId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetPremiumSeatsAsync(seatHallId, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Seat", $"SeatHallId: '{seatHallId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-disabled-access/{seatHallId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetDisabledAccessResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetDisabledAccessAsync(int seatHallId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetDisabledAccessAsync(seatHallId, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Seat", $"SeatHallId: '{seatHallId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-available-by-row/{seatHallId:int}/{seatRowNumber}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetAvailableByRowResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetAvailableByRowAsync(int seatHallId, string seatRowNumber, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetAvailableByRowAsync(seatHallId, seatRowNumber, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "Seat", $"SeatHallId: '{seatHallId}', SeatRowNumber: '{seatRowNumber}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-category-breakdown/{seatHallId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetCategoryBreakdownResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetCategoryBreakdownAsync(int seatHallId)
        {
            var response = await service.GetCategoryBreakdownAsync(seatHallId);
            if (HandleResponseError(response, logger, "Seat", $"SeatHallId: '{seatHallId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("mark-reserved/{seatId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> MarkReservedAsync(int seatId, [FromBody] MarkReservedRequestDto updateRequest)
        {
            var response = await service.MarkReservedAsync(seatId, updateRequest);
            if (HandleResponseError(response, logger, "Seat", $"SeatId: '{seatId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("mark-sold/{seatId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> MarkSoldAsync(int seatId, [FromBody] MarkSoldRequestDto updateRequest)
        {
            var response = await service.MarkSoldAsync(seatId, updateRequest);
            if (HandleResponseError(response, logger, "Seat", $"SeatId: '{seatId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("mark-available/{seatId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> MarkAvailableAsync(int seatId, [FromBody] MarkAvailableRequestDto updateRequest)
        {
            var response = await service.MarkAvailableAsync(seatId, updateRequest);
            if (HandleResponseError(response, logger, "Seat", $"SeatId: '{seatId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("block-seat/{seatId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> BlockSeatAsync(int seatId, [FromBody] BlockSeatRequestDto updateRequest)
        {
            var response = await service.BlockSeatAsync(seatId, updateRequest);
            if (HandleResponseError(response, logger, "Seat", $"SeatId: '{seatId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}