// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirBilet.Application.Contracts;
using QuickCode.BirBilet.VenueManagementModule.Domain.Entities;
using QuickCode.BirBilet.VenueManagementModule.Application.Interfaces.Repositories;
using QuickCode.BirBilet.VenueManagementModule.Application.Dtos.Seat;
using QuickCode.BirBilet.VenueManagementModule.Domain.Enums;

namespace QuickCode.BirBilet.VenueManagementModule.Application.Services.Seat
{
    public partial class SeatService : ISeatService
    {
        private readonly ILogger<SeatService> _logger;
        private readonly ISeatRepository _repository;
        public SeatService(ILogger<SeatService> logger, ISeatRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<SeatDto>> InsertAsync(SeatDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(SeatDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, SeatDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<SeatDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<SeatDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByHallResponseDto>>> GetByHallAsync(int seatHallId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByHallAsync(seatHallId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetAvailableResponseDto>>> GetAvailableAsync(int seatHallId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetAvailableAsync(seatHallId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByCategoryResponseDto>>> GetByCategoryAsync(int seatHallId, SeatCategoryKind seatCategory, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByCategoryAsync(seatHallId, seatCategory, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetPremiumSeatsResponseDto>>> GetPremiumSeatsAsync(int seatHallId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetPremiumSeatsAsync(seatHallId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetDisabledAccessResponseDto>>> GetDisabledAccessAsync(int seatHallId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetDisabledAccessAsync(seatHallId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetAvailableByRowResponseDto>>> GetAvailableByRowAsync(int seatHallId, string seatRowNumber, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetAvailableByRowAsync(seatHallId, seatRowNumber, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetCategoryBreakdownResponseDto>> GetCategoryBreakdownAsync(int seatHallId)
        {
            var returnValue = await _repository.GetCategoryBreakdownAsync(seatHallId);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> MarkReservedAsync(int seatId, MarkReservedRequestDto updateRequest)
        {
            var returnValue = await _repository.MarkReservedAsync(seatId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> MarkSoldAsync(int seatId, MarkSoldRequestDto updateRequest)
        {
            var returnValue = await _repository.MarkSoldAsync(seatId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> MarkAvailableAsync(int seatId, MarkAvailableRequestDto updateRequest)
        {
            var returnValue = await _repository.MarkAvailableAsync(seatId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> BlockSeatAsync(int seatId, BlockSeatRequestDto updateRequest)
        {
            var returnValue = await _repository.BlockSeatAsync(seatId, updateRequest);
            return returnValue.ToResponse();
        }
    }
}